const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Admin1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const target=process.argv[2]||'https://duf5391-ux.github.io/ielts-learning/',label=process.argv[3]||'before',here=__dirname;
const book='C:/Users/Admin1/Documents/Codex/2026-09-12/referenced-chatgpt-conversation-this-is-an/outputs/IELTS-四科学习册';
const routes=['study','vocabulary-review','word-review','sentence-learning','practice','tests','writing-workbench','workspace','topical-vocabulary'];
let server,browser;const errors=[],rows=[];
(async()=>{let base=target;if(!target.startsWith('http')){const file=path.resolve(target);server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html',dest=rel==='index.html'?file:path.resolve(book,rel);if(![path.dirname(file),book].some(p=>dest.startsWith(p))||!fs.existsSync(dest)){res.writeHead(404).end();return}res.writeHead(200,{'Content-Type':({'.html':'text/html;charset=utf-8','.js':'application/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(dest)]||'application/octet-stream'});fs.createReadStream(dest).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/'}
browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext();await ctx.addInitScript(()=>{localStorage.setItem('ielts-finished-book-v1',JSON.stringify({version:1,fields:{'lookup-history-v1':JSON.stringify([{term:'sustainable',key:'sustainable',meaning:'可持续的',favorite:true,lookupVersion:2,review:{dueAt:'2020-01-01T00:00:00Z'}},{term:'resilient',key:'resilient',meaning:'有韧性的；能恢复的',favorite:true,lookupVersion:2},{term:'perspective',key:'perspective',meaning:'观点；视角',favorite:true,lookupVersion:2}]),'sentence-collection-v1':JSON.stringify([{text:'Education creates opportunities for people from all walks of life.',translation:'教育为各行各业的人创造机会。',direction:'en|zh-CN',sourceRoute:'topic-education',title:'教育与机会'}])},snapshots:{}}))});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'#study',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.getElementById('vr-start')&&!document.body.hasAttribute('data-progressive-state'),null,{timeout:120000});
for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});for(const route of routes){await page.evaluate(id=>location.hash=id,route);await page.waitForTimeout(180);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(here,`${label}-${width}-${route}.png`)});rows.push(await page.evaluate(({route,width})=>({route,width,title:document.title,headings:[...document.querySelectorAll('main h1,main h2')].filter(n=>n.checkVisibility()).slice(0,5).map(n=>n.innerText),nav:[...document.querySelectorAll('#workspace-navigation [data-go]')].map(n=>({id:n.dataset.go,text:n.innerText})),overflow:document.documentElement.scrollWidth>innerWidth,activePanels:[...document.querySelectorAll('main>.panel')].filter(n=>!n.hidden).map(n=>n.id)}),{route,width}));}}
fs.writeFileSync(path.join(here,label+'-probe.json'),JSON.stringify({target,at:new Date().toISOString(),rows,errors},null,2));console.log(JSON.stringify({pages:rows.length,errors,overflows:rows.filter(r=>r.overflow)}));await ctx.close();})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server?.close()});
