const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Admin1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const here=__dirname,book='C:/Users/Admin1/Documents/Codex/2026-09-12/referenced-chatgpt-conversation-this-is-an/outputs/IELTS-四科学习册';
const target=process.argv[2]||path.join(here,'candidate.html'),report={target,source_sha256:require('crypto').createHash('sha256').update(fs.readFileSync(path.join(here,'candidate.html'))).digest('hex'),at:new Date().toISOString(),checks:[],routes:[],errors:[]};
let server,browser,page;
const check=(name,value)=>{assert(value,name);report.checks.push(name)};
(async()=>{
let base=target;if(!target.startsWith('http')){const file=path.resolve(target),root=path.basename(file)==='index.html'?path.dirname(file):book;server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html',dest=rel==='index.html'?file:path.resolve(root,rel);if(![path.dirname(file),root].some(p=>dest.startsWith(p))||!fs.existsSync(dest)){res.writeHead(404).end();return}res.writeHead(200,{'Content-Type':({'.html':'text/html;charset=utf-8','.js':'application/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(dest)]||'application/octet-stream'});fs.createReadStream(dest).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/'}
browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});page=await ctx.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>report.errors.push(e.message));
const ready=async p=>{await p.waitForFunction(()=>document.querySelector('#word-learn-card .ui-learn-term')&&document.querySelector('#ui-spelling-check')&&!document.body.hasAttribute('data-progressive-state'),null,{timeout:120000})};
const go=async id=>{await page.evaluate(id=>location.hash=id,id);await page.waitForFunction(id=>{const n=document.getElementById(id);return n?.checkVisibility()},id);await page.waitForTimeout(100)};
const rows=()=>page.evaluate(()=>JSON.parse(document.getElementById('lookup-history-store').value||'[]'));
const shot=async name=>{await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(here,name+'.png'),animations:'disabled',timeout:12000})};
await page.goto(base+'#vocabulary-review',{waitUntil:'domcontentloaded'});await ready(page);
check('fresh word entry opens curriculum without selection',await page.locator('.ui-learn-term').innerText()==='curriculum');
check('only six primary entries',await page.locator('#workspace-navigation [data-go]').count()===6);
check('word section has learning review sentences and history',await page.locator('#vocabulary-review .ui-word-tabs a').count()===4);
await shot('after-1440-vocabulary-review');
await page.locator('[data-learn-grade=known]').click();
let r=await rows();check('direct grade creates study event without favorite',r[0].term==='curriculum'&&r[0].learningEvents.length===1&&!r[0].favorite&&r[0].learningEvents[0].independentAttempt);
check('study marks newly studied, never automatically mastered',await page.locator('[data-save="topic-vocab-level-education-curriculum"]').inputValue()==='N');
const second=await page.locator('.ui-learn-term').innerText();check('grade advances to next word',second!=='curriculum');
await page.locator('#word-learn-reveal').click();await page.reload({waitUntil:'domcontentloaded'});await ready(page);await page.locator('[data-learn-grade=known]').click();r=await rows();check('hinted learning still does not earn independent streak after reload',r[0].term===second&&!r[0].learningEvents[0].independentAttempt&&r[0].review.successfulStreak===0);
await page.reload({waitUntil:'domcontentloaded'});await ready(page);check('reload resumes after saved words',!['curriculum',second].includes(await page.locator('.ui-learn-term').innerText()));
await page.locator('#word-learn-topic').selectOption('environment');check('topic changes immediately to its next word',await page.locator('.ui-topic-pill').innerText()==='环境与自然');
await page.reload({waitUntil:'domcontentloaded'});await ready(page);check('topic preference survives refresh',await page.locator('#word-learn-topic').inputValue()==='environment');
const beforeFailure=await page.locator('.ui-learn-term').innerText(),historyBefore=await page.locator('#lookup-history-store').inputValue();
await page.evaluate(()=>{window.testSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='ielts-finished-book-v1')throw new DOMException('probe quota','QuotaExceededError');return window.testSetItem.call(this,k,v)}});
await page.locator('[data-learn-grade=forgot]').click();check('failed storage does not advance or overwrite history',await page.locator('.ui-learn-term').innerText()===beforeFailure&&await page.locator('#lookup-history-store').inputValue()===historyBefore);check('failed save has visible explanation',(await page.locator('#word-learn-status').innerText()).includes('没能保存'));
await page.evaluate(()=>Storage.prototype.setItem=window.testSetItem);await page.locator('[data-learn-grade=forgot]').click();check('retry saves and advances',await page.locator('.ui-learn-term').innerText()!==beforeFailure);
// An actual lookup creates a non-favorite word and makes it reviewable.
await page.locator('#lookup-open').click();await page.locator('#lookup-input').fill('sustainable');await page.locator('#lookup-form').evaluate(n=>n.requestSubmit());await page.waitForFunction(()=>window.IELTSLookup.getHistory().some(x=>x.term==='sustainable'));
await page.locator('#lookup-close').click();await go('word-review');
r=await rows();check('looked-up word enters review without collecting',r.some(x=>x.term==='sustainable'&&!x.favorite));check('review stats include every learned or queried word',Number(await page.locator('#vr-stats strong').first().innerText())===r.length);
await page.locator('#vr-start').click();check('review starts from automatic queue',await page.locator('#vr-stage').isVisible());await page.locator('[data-vr-grade=hard]').click();check('review event is saved',(await rows()).some(x=>x.reviews?.length));
await page.locator('#ui-spelling-check').click();await page.locator('#vr-spelling').fill('deliberately-wrong');await page.locator('#vr-spelling').evaluate(n=>n.form.requestSubmit());check('wrong spelling cannot be graded independently known',await page.locator('[data-vr-grade=known]').isDisabled());await page.locator('[data-vr-grade=forgot]').click();
await go('review-history');check('real learning and spelling events are visible',await page.locator('.ui-history-row').count()>=5);await page.locator('#ui-history-mode').selectOption('spelling');check('history retains exact spelling input',(await page.locator('#ui-review-history').innerText()).includes('deliberately-wrong'));await shot('after-1440-review-history');
await go('sentence-learning');check('sentence view highlights vocabulary owner',await page.locator('#workspace-navigation [aria-current]').getAttribute('data-go')==='vocabulary-review');check('existing sentence tool is present',await page.locator('[data-open-sentence]').first().isVisible());
await go('word-library');check('library contains query and learning without favorite gate',await page.locator('.vr-list-card').count()===r.length);
// A second isolated profile exercises old records; migration must not invent dates/events.
const old=await browser.newContext();await old.addInitScript(()=>localStorage.setItem('ielts-finished-book-v1',JSON.stringify({version:1,fields:{'topic-vocab-level-education-curriculum':'K','lookup-history-v1':JSON.stringify([{term:'resilient',key:'resilient',favorite:false,count:1,lastAt:'2020-01-01T00:00:00Z',meaning:'有韧性的'}]),'sentence-collection-v1':JSON.stringify([{text:'Education opens doors.',translation:'教育打开机会之门。',direction:'en|zh-CN',sourceRoute:'topic-education',title:'教育'}])},snapshots:{}})));
const op=await old.newPage();await op.goto(base+'#vocabulary-review',{waitUntil:'domcontentloaded'});await ready(op);
const legacy=await op.evaluate(()=>window.IELTSLookup.getHistory().find(x=>x.term==='curriculum'));check('old marked words enter review without invented events',legacy.learning.legacyMarked&&!legacy.learningEvents&&!legacy.learning.lastAt);check('old mastery and sentence record remain unchanged',await op.locator('[data-save="topic-vocab-level-education-curriculum"]').inputValue()==='K'&&(await op.locator('#sentence-store').inputValue()).includes('Education opens doors.'));await old.close();
// All changed route surfaces, desktop and phone viewport, one at a time.
for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});for(const id of ['study','vocabulary-review','word-review','sentence-learning','lookup-learning','review-history','word-library','practice','tests','writing-workbench','workspace','topical-vocabulary']){await go(id);const state=await page.evaluate(id=>({id,width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,active:[...document.querySelectorAll('main>.panel')].filter(n=>!n.hidden).map(n=>n.id),title:document.title}),id);report.routes.push(state);check(`${width} ${id} has one active panel and no overflow`,state.active.length===1&&!state.overflow);await shot(`after-${width}-${id}`)}}
await go('vocabulary-review');await page.evaluate(()=>window.scrollTo(0,0));const gradeBox=await page.locator('.ui-learn-grades').boundingBox(),bottomBar=await page.locator('#product-mobile-nav').boundingBox();check('phone default grade buttons are fully above bottom navigation',gradeBox.y+gradeBox.height<bottomBar.y);
await page.locator('#product-more').click();check('phone more drawer exposes self tests and resources',await page.locator('#workspace-navigation [data-go=tests]').isVisible()&&await page.locator('#workspace-navigation [data-go=workspace]').isVisible());await page.locator('#workspace-navigation [data-go=tests]').click();check('drawer route works and closes',await page.locator('#mobile-menu').getAttribute('aria-expanded')==='false');
await go('guide');await page.locator('[data-ds-skill="reading"]').click();await page.locator('#ds-start').click();await page.waitForTimeout(150);const dock=await page.locator('#daily-study-dock').boundingBox();check('daily controls do not overlap new phone navigation',dock.y+dock.height<bottomBar.y);await page.locator('#hs-rest').click();await page.waitForFunction(()=>JSON.parse(document.getElementById('daily-study-state').value).session.status==='paused');check('rest still pauses daily actions',await page.locator('#ds-next').isDisabled());await page.locator('#ds-pause').click();await page.locator('#hs-finish').click();await page.reload({waitUntil:'domcontentloaded'});await ready(page);check('word history survives daily rest finish and reload',(await rows()).some(x=>x.learningEvents?.length));
check('no uncaught browser errors',report.errors.length===0);report.pass=true;await ctx.close();
})().catch(async e=>{report.pass=false;report.error=e.stack;console.error(e);try{await page?.screenshot({path:path.join(here,'failure.png'),timeout:5000})}catch{}process.exitCode=1}).finally(async()=>{fs.writeFileSync(path.join(here,target.startsWith('http')?'live-verification.json':path.basename(target)==='index.html'?'packed-verification.json':'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,routes:report.routes.length,errors:report.errors,error:report.error}));await browser?.close();server?.close()});
