const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Admin1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const here=__dirname,book='C:/Users/Admin1/Documents/Codex/2026-09-12/referenced-chatgpt-conversation-this-is-an/outputs/IELTS-四科学习册';
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.json':'application/json','.mp3':'audio/mpeg','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const checks=[],errors=[];let browser,server;
const seed=[['education','education: the process of teaching'],['evidence','information supporting a conclusion'],['curriculum','a course of study']].map(([term,meaning])=>({key:term,term,meaning,favorite:true,status:'pending',lastAt:'2020-01-01T00:00:00Z',favoriteAt:'2020-01-01T00:00:00Z',custom:'keep-'+term}));
const add=(name,detail)=>checks.push({name,detail,status:'pass'});
const stored=page=>page.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('ielts-finished-book-v1')).fields['lookup-history-v1']));
async function main(){
 server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1);const file=rel===''||rel==='index.html'?path.join(here,'candidate.html'):path.resolve(book,rel);if(!file.startsWith(book)&&file!==path.join(here,'candidate.html')){res.writeHead(403).end();return;}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1280,height:900}});
 await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
 await context.addInitScript(seed=>{if(!localStorage.getItem('vocab-feature-seeded')){localStorage.setItem('ielts-finished-book-v1',JSON.stringify({version:1,fields:{'lookup-history-v1':JSON.stringify(seed),'workspace-reflection':'unrelated retained'},snapshots:{}}));localStorage.setItem('vocab-feature-seeded','1');}},seed);
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/#topical-vocabulary');await page.waitForSelector('#topical-vocabulary[data-tv-ready="true"]');
 const first=page.locator('.tv-card[data-tv-id="education-curriculum"]');await first.locator('[data-vq-value="K"]').waitFor();
 assert(await first.locator('select').isHidden());assert(await page.locator('.vq-choices').count()<=25);add('Only visible word cards gain direct buttons; saved selects preserved');
 for(const value of ['N','R','K']){await first.locator(`[data-vq-value="${value}"]`).click();assert.equal(await first.locator('select').inputValue(),value);assert.equal(await first.locator(`[data-vq-value="${value}"]`).getAttribute('aria-pressed'),'true');}
 await page.reload();await first.locator('[data-vq-value="K"]').waitFor();assert.equal(await first.locator('select').inputValue(),'K');assert.equal(await first.locator('[data-vq-value="K"]').getAttribute('aria-pressed'),'true');add('Direct familiarity choices persist and restore without opening a dropdown');
 await page.locator('#tv-status').selectOption('K');assert.equal(await page.locator('.tv-card:visible').count(),1);await first.locator('[data-vq-value=""]').click();await page.waitForFunction(()=>document.querySelector('#tv-empty').hidden===false);add('Clear while filtered removes the card and refreshes count');await page.locator('#tv-status').selectOption('all');
 await page.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='ielts-finished-book-v1')throw Error('quota fixture');return window.originalSet.call(this,k,v);};});
 await first.locator('[data-vq-value="K"]').click();assert.equal(await first.locator('select').inputValue(),'');assert.match(await page.locator('.vq-notice').innerText(),/未保存/);await page.evaluate(()=>Storage.prototype.setItem=window.originalSet);add('Failed quick mark keeps prior state');
 await page.goto(base+'/#vocabulary-review');await page.locator('#vr-start').waitFor();const education=page.locator('.vr-list-card[data-vr-key="education"]');await education.locator('[data-vr-quick-grade="known"]').click();let rows=await stored(page);assert.equal(rows[0].selfAssessment.grade,'known');assert.equal(rows[0].review,undefined);assert.equal(rows[0].custom,'keep-education');add('List self-assessment is direct and does not create a review or change schedule');
 await page.locator('#vr-start').click();assert.equal(await page.locator('#vr-stage .vr-meaning').count(),0);await page.locator('#vr-stage [data-vr-grade="known"]').click();rows=await stored(page);assert.equal(rows[0].reviews[0].answerRevealed,false);assert.equal(rows[0].reviews[0].independentAttempt,true);assert.equal(rows[0].review.successfulStreak,1);add('Recall can be graded before revealing; evidence stored independently');
 await page.locator('#vr-stage [data-vr-grade="forgot"]').click();rows=await stored(page);assert.equal(rows[1].review.intervalMinutes,10);await page.getByRole('button',{name:'查看释义与原句',exact:true}).click();await page.locator('#vr-stage [data-vr-grade="known"]').click();rows=await stored(page);assert.equal(rows[2].reviews[0].answerRevealed,true);assert.equal(rows[2].reviews[0].independentAttempt,false);assert.equal(rows[2].review.successfulStreak,0);add('Revealed answers never count as unaided successful recall');
 await page.getByRole('button',{name:'返回单词表',exact:true}).click();await page.locator('#vr-practice-all').click();const before=JSON.stringify(await stored(page)),beforeWord=await page.locator('#vr-stage .vr-word').innerText();
 await page.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='ielts-finished-book-v1')throw Error('quota fixture');return window.originalSet.call(this,k,v);};});await page.locator('#vr-stage [data-vr-grade="known"]').click();assert.equal(JSON.stringify(await stored(page)),before);assert.equal(await page.locator('#vr-stage .vr-word').innerText(),beforeWord);assert.match(await page.locator('#vr-status').innerText(),/未保存/);await page.evaluate(()=>Storage.prototype.setItem=window.originalSet);add('Failed review does not advance or leave hidden schedule changes');
 await page.getByRole('button',{name:'暂停本轮',exact:true}).click();await page.locator('#vr-mode').selectOption('spelling');await education.getByRole('button',{name:'复习这个词',exact:true}).click();assert.doesNotMatch(await page.locator('.vr-prompt').innerText(),/education/i);await page.locator('#vr-spelling').fill('educaton');await page.getByRole('button',{name:'核对拼写',exact:true}).click();assert(await page.locator('[data-vr-grade="known"]').isDisabled());await page.locator('[data-vr-grade="forgot"]').click();add('Spelling does not leak headword; wrong spelling cannot be marked independently correct');
 await page.getByRole('button',{name:'返回单词表',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.goto(base+'/#topical-vocabulary');await first.locator('[data-vq-value="K"]').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await first.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(here,'vocabulary-mobile.png')});add('390px direct controls fit and keep existing mobile navigation');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ielts-finished-book-v1')).fields['workspace-reflection']),'unrelated retained');assert.deepEqual(errors,[]);
 await context.close();
}
main().then(()=>{fs.writeFileSync(path.join(here,'vocabulary-qa.json'),JSON.stringify({pass:true,checks,errors},null,2));console.log(JSON.stringify({pass:true,checks},null,2));}).catch(e=>{fs.writeFileSync(path.join(here,'vocabulary-qa.json'),JSON.stringify({pass:false,checks,errors,error:e.stack},null,2));console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server?.close();});
