const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),crypto=require('crypto');
const {chromium}=require('C:/Users/Admin1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const here=__dirname,book='C:/Users/Admin1/Documents/Codex/2026-09-12/referenced-chatgpt-conversation-this-is-an/outputs/IELTS-四科学习册',target=process.argv[2]||'candidate',live=target.startsWith('https:'),checks=[],errors=[];let browser,server;
const add=(name)=>{checks.push(name);console.log(name)};
const ready=page=>page.waitForFunction(()=>window.IELTSLookup&&window.IELTSRecordStore&&document.getElementById('vr-start')&&!document.body.hasAttribute('data-progressive-state'),null,{timeout:120000});
const go=async(page,id)=>{await page.evaluate(id=>location.hash=id,id);await page.waitForFunction(id=>{const t=document.getElementById(id);return t&&!t.closest('main>.panel')?.hidden&&location.hash==='#'+id},id)};
const state=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('ielts-finished-book-v1')).fields);
async function main(){let base=target;if(!live){const packed=target==='candidate'?null:path.resolve(target);server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html';const file=packed?path.resolve(packed,rel):rel==='index.html'?path.join(here,'candidate.html'):path.resolve(book,rel);if(![packed||book,here].some(root=>file.startsWith(root+path.sep)||file.startsWith(root+'/'))||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return}res.writeHead(200,{'Content-Type':({'.html':'text/html;charset=utf-8','.js':'application/javascript','.json':'application/json','.css':'text/css','.mp3':'audio/mpeg'})[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/'}
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.addInitScript(()=>{if(localStorage.getItem('word-split-fixture'))return;localStorage.setItem('word-split-fixture','1');localStorage.setItem('ielts-finished-book-v1',JSON.stringify({version:1,fields:{'lookup-history-v1':JSON.stringify([{term:'sustainable',key:'sustainable',meaning:'可持续的',favorite:true,lookupVersion:2,review:{dueAt:'2020-01-01T00:00:00Z'},reviews:[]}]),'sentence-collection-v1':JSON.stringify([{text:'Education creates opportunities.',translation:'教育创造机会。',direction:'en|zh-CN',createdAt:'2026-09-19T00:00:00Z'}]),'workspace-reflection':'word separation keeps old notes'},snapshots:{}}));});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(base+'#vocabulary-review',{waitUntil:'domcontentloaded'});await ready(page);add('Initialized exact page '+crypto.createHash('sha256').update(await response.body()).digest('hex'));
 assert.equal(await page.locator('[data-save]').count(),3371);
 for(const [route,label] of [['vocabulary-review','单词'],['word-review','复习'],['sentence-learning','句子']]){const b=page.locator('#workspace-navigation [data-go="'+route+'"]');assert.equal(await b.innerText(),label);await b.click();await go(page,route);assert.equal(await b.getAttribute('aria-current'),'page');assert.equal(await page.locator('main>.panel:not([hidden])').count(),1)}add('三个独立一级入口各自高亮并只显示自己的页面');
 await go(page,'vocabulary-review');assert(await page.locator('#vr-list').isVisible());assert(await page.locator('#vr-start').isHidden());assert.equal(await page.locator('#vocabulary-review .la-section-links').count(),0);assert.equal(await page.locator('#learning-tools a[href="#vocabulary-review"]').count(),0);
 await page.locator('[data-vr-quick-grade="known"]').click();assert.match(await page.locator('#word-list-status').innerText(),/已标记/);let saved=JSON.parse((await state(page))['lookup-history-v1']);assert.equal(saved[0].reviews.length,0);assert.equal(saved[0].review.dueAt,'2020-01-01T00:00:00Z');add('单词页直接标记可见，未伪造复习记录或改到期时间');
 await page.getByRole('button',{name:'复习这个词',exact:true}).click();await page.waitForURL('**/#word-review');assert(await page.locator('#vr-stage').isVisible());assert(await page.locator('#vr-list').isHidden());await page.locator('[data-vr-grade="known"]').click();await page.getByRole('button',{name:'返回单词表',exact:true}).click();await page.waitForURL('**/#vocabulary-review');assert(await page.locator('#vr-list').isVisible());
 await page.reload({waitUntil:'domcontentloaded'});await ready(page);saved=JSON.parse((await state(page))['lookup-history-v1']);assert.equal(saved[0].reviews.length,1);add('从单词进入独立复习页，完成返回原表，刷新保留同一份历史');
 await go(page,'topical-vocabulary');const star=page.locator('.tv-card[data-tv-id="education-curriculum"] input[data-save^="topic-vocab-star-"]');await star.check();await go(page,'vocabulary-review');assert.equal(await page.locator('#vr-list .vr-list-card').count(),2);const card=page.locator('#vr-list .vr-list-card').filter({has:page.getByRole('heading',{name:'curriculum',exact:true})});assert(await card.isVisible());await card.getByRole('button',{name:'取消收藏',exact:true}).click();await go(page,'topical-vocabulary');assert.equal(await star.isChecked(),false);await page.reload({waitUntil:'domcontentloaded'});await ready(page);assert.equal(await star.isChecked(),false);add('话题词卡收藏进入单词表，取消同步，刷新不会重新出现');
 // Simulate a failed save: checkbox and history must both stay unchanged.
 if(!live){await page.evaluate(()=>{window.__originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='ielts-finished-book-v1')throw new DOMException('isolated quota fixture','QuotaExceededError');return window.__originalSetItem.call(this,k,v)}});await star.click();assert.equal(await star.isChecked(),false);await page.evaluate(()=>{Storage.prototype.setItem=window.__originalSetItem});assert.equal(JSON.parse((await state(page))['lookup-history-v1']).find(x=>x.term==='curriculum').favorite,false);add('保存失败时收藏勾选和词库一起回退');}
 await go(page,'sentence-learning');assert.match(await page.locator('#sentence-list').innerText(),/Education creates/);assert.equal((await state(page))['workspace-reflection'],'word separation keeps old notes');add('旧句子和其他记录保留');
 for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});for(const route of ['vocabulary-review','word-review','sentence-learning']){if(width===390){await page.locator('#mobile-menu').click();const b=page.locator('#workspace-navigation [data-go="'+route+'"]');await b.click();await page.waitForTimeout(100);assert.equal(await page.locator('#mobile-menu').getAttribute('aria-expanded'),'false')}else await go(page,route);assert.equal(new URL(page.url()).hash,'#'+route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(here,`${live?'live':'candidate'}-${width}-${route}.png`)});}add('桌面和手机入口、抽屉收起与页面布局通过');}
 assert.deepEqual(errors,[]);await context.close();}
main().then(()=>fs.writeFileSync(path.join(here,`qa-${live?'live':target==='candidate'?'candidate':'packed'}.json`),JSON.stringify({pass:true,target,checks,errors,at:new Date().toISOString()},null,2))).catch(e=>{console.error(e);fs.writeFileSync(path.join(here,'qa-failure.json'),JSON.stringify({pass:false,target,checks,errors,error:e.stack},null,2));process.exitCode=1}).finally(async()=>{await browser?.close();server?.close()});
