// Read-only deployment verification; browser storage is an isolated synthetic profile.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Admin1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const expected=JSON.parse(fs.readFileSync(path.join(__dirname,'../github-publication/manifest.json'),'utf8'));
const checks=[],errors=[],url='https://duf5391-ux.github.io/ielts-learning/';
const ready=p=>p.waitForFunction(()=>window.IELTSLookup&&document.getElementById('vr-start')&&!document.body.hasAttribute('data-progressive-state'),null,{timeout:120000});
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const context=await browser.newContext({viewport:{width:1440,height:1000}});
await context.addInitScript(()=>{if(localStorage.getItem('standalone-final-probe'))return;localStorage.setItem('standalone-final-probe','1');localStorage.setItem('ielts-finished-book-v1',JSON.stringify({version:1,fields:{'lookup-history-v1':JSON.stringify([{key:'sustainable',term:'sustainable',meaning:'可持续的',lookupVersion:2,favorite:true,review:{dueAt:'2020-01-01T00:00:00Z'},reviews:[]}]),'sentence-collection-v1':JSON.stringify([{text:'Education creates opportunities.',translation:'教育创造机会。',direction:'en|zh-CN'}])},snapshots:{}}));});
const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));const response=await p.goto(url+'#vocabulary-review',{waitUntil:'domcontentloaded'});assert.equal(response.status(),200);assert.equal(crypto.createHash('sha256').update(await response.body()).digest('hex'),expected.published_html_sha256);await ready(p);assert.equal(await p.locator('[data-save]').count(),expected.save_fields);checks.push('Live fingerprint matches latest successful publication; all saved fields assembled');
for(const width of [1440,390]){await p.setViewportSize({width,height:width===390?844:1000});for(const route of ['vocabulary-review','word-review','sentence-learning']){const link=width===390?p.locator('#product-mobile-nav a[href="#'+route+'"]'):p.locator('#workspace-navigation [data-go="'+route+'"]');assert(await link.isVisible());await link.click();await p.waitForFunction(id=>location.hash==='#'+id&&!document.getElementById(id).hidden,route);assert.equal(await p.locator('main>.panel:not([hidden])').count(),1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(__dirname,`latest-live-${width}-${route}.png`)});}checks.push(width+'px: words/review/sentences visible and one click away');}
await p.locator('#product-mobile-nav a[href="#vocabulary-review"]').click();await p.locator('[data-vr-quick-grade="known"]').click();assert.match(await p.locator('#word-list-status').innerText(),/已标记/);assert(await p.locator('#vr-start').isHidden());await p.locator('#product-mobile-nav a[href="#word-review"]').click();await p.locator('#vr-start').click();assert(await p.locator('#vr-stage').isVisible());assert(await p.locator('#vr-list').isHidden());await p.locator('[data-vr-grade="known"]').click();await p.reload({waitUntil:'domcontentloaded'});await ready(p);const rows=await p.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('ielts-finished-book-v1')).fields['lookup-history-v1']));assert.equal(rows[0].reviews.length,1);checks.push('Direct self-assessment and separate review work, share one history and survive reload');
await p.locator('#product-mobile-nav a[href="#sentence-learning"]').click();assert.match(await p.locator('#sentence-list').innerText(),/Education creates opportunities/);assert.deepEqual(errors,[]);
const report={pass:true,url,sourceSha256:expected.source_html_sha256,liveSha256:expected.published_html_sha256,at:new Date().toISOString(),checks,errors};fs.writeFileSync(path.join(__dirname,'latest-live-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await context.close();}finally{await browser.close()}})().catch(e=>{console.error(e);fs.writeFileSync(path.join(__dirname,'latest-live-failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));process.exitCode=1});
