const {start,fs,path}=require('../product-repair-20260922/qa/journey-lib.cjs'),assert=require('node:assert/strict'),crypto=require('crypto');
const target=process.argv[2]||'candidate',packed=target==='packed',live=target.startsWith('https:'),file=path.join(__dirname,'candidate.html');
(async()=>{const e=await start({file,packed,width:1440}),p=e.page,checks=[],shots=[],report={target,source_sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),errors:e.errors};p.setDefaultTimeout(15000);if(live)await e.context.unroute('**/*');const base=live?target:e.base;
const check=(name,ok)=>{assert(ok,name);checks.push(name)};
const go=async id=>{await e.go(id);await p.waitForFunction(id=>{const n=document.getElementById(id);return n?.checkVisibility()},id)};
const shot=async name=>{await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(__dirname,`${live?'live':packed?'packed':'after'}-${name}.png`),animations:'disabled',timeout:12000});const s=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,active:[...document.querySelectorAll('main>.panel')].filter(n=>!n.hidden).map(n=>n.id)}));check(name+' no overflow and one active panel',!s.overflow&&s.active.length===1);shots.push({name,...s})};
try{
await p.goto(base+'#tests',{waitUntil:'domcontentloaded'});await e.ready();await p.waitForFunction(()=>document.getElementById('ux-test-summary')?.children.length===3);
check('four subject cards expose real status and history',await p.locator('[data-ux-test]').count()===4&&await p.locator('.ux-test-status').allTextContents().then(a=>a.every(t=>t==='尚未开始')));await shot('1440-tests');
await p.locator('[data-ux-test=reading] .ux-test-start').click();await p.locator('[data-test-start=reading]').click();await p.locator('[data-save="full-test-reading-q1"]').fill('isolated-upgrade-answer');await go('tests');check('self test card shows progress from actual saved answer',(await p.locator('[data-ux-test=reading] .ux-test-status').innerText()).includes('1 / 40'));
await p.locator('[data-ux-test=reading] .ux-test-start').click();p.once('dialog',d=>d.accept());await p.locator('[data-test-submit=reading]').click();check('submitted answers lock',await p.locator('[data-save="full-test-reading-q1"]').getAttribute('readonly')!==null);await p.locator('.ux-history-jump[data-ux-history=reading]').click();await p.waitForFunction(()=>document.getElementById('ux-test-history-reading').open);check('latest submitted result appears in history immediately',await p.locator('#ux-test-history-reading .ux-current-result').isVisible());p.once('dialog',d=>d.accept());await p.locator('[data-test-retry=reading]').click();await go('tests');await p.locator('[data-ux-test=reading] [data-ux-history]').click();await p.waitForFunction(()=>document.getElementById('ux-test-history-reading').open);check('history link opens exact history and retains previous answer',(await p.locator('#ux-test-history-reading').innerText()).includes('isolated-upgrade-answer'));await shot('1440-test-history');
await go('test-reading');await p.locator('[data-test-start=reading]').click();await shot('1440-test-reading-active');
await p.setViewportSize({width:390,height:844});await go('test-reading');await p.locator('#ux-reading-part-1 [data-ux-view=answers]').click();check('phone answer mode shows original fields and hides paper',await p.locator('[data-save="full-test-reading-q1"]').isVisible()&&await p.locator('#ux-reading-part-1-paper').isHidden());await p.locator('[data-save="full-test-reading-q1"]').fill('retained-mobile-draft');await p.locator('#ux-reading-part-1 [data-ux-view=paper]').click();check('switch back shows paper without clearing answer',await p.locator('#ux-reading-part-1-paper').isVisible()&&await p.locator('[data-save="full-test-reading-q1"]').inputValue()==='retained-mobile-draft');await p.reload();await e.ready();check('paper answer draft survives reload',await p.locator('[data-save="full-test-reading-q1"]').inputValue()==='retained-mobile-draft');
await go('test-writing');await p.locator('[data-test-start=writing]').click();await p.locator('#ux-writing-part-1 [data-ux-view=answers]').click();const essay=p.locator('#test-writing [data-test-answer=writing]').first();await essay.fill('This separate self-test essay remains saved while switching views.');await p.locator('#ux-writing-part-1 [data-ux-view=paper]').click();check('writing self test preserves essay between prompt and answer views',(await essay.inputValue()).includes('separate self-test'));await shot('390-test-writing');
await go('writing-workbench');await p.locator('#ux-writing-progress').selectOption('started');check('writing empty filter is clear and reversible',await p.locator('#ux-writing-empty').isVisible());await p.locator('#ux-writing-clear').click();check('clear filter restores 32 actual writing tasks',await p.locator('[data-ww-pick]:visible').count()===32);await p.locator('[data-ww-pick]').first().click();await p.waitForTimeout(200);const id=await p.locator('[data-ww-unit]:visible').getAttribute('id');await p.locator('[data-save="'+id+'-first"]').fill('This is a saved draft for the interaction upgrade.');await p.locator('[data-ww-catalogue]:visible').click();await p.locator('#ux-writing-progress').selectOption('started');check('writing filter and badge reflect existing draft',await p.locator('[data-ww-pick]:visible').count()===1&&(await p.locator('[data-ww-pick]:visible .ux-writing-badge').innerText())==='首稿写作中');await p.locator('[data-ww-pick]:visible').click();check('writing reopens same saved draft',(await p.locator('[data-save="'+id+'-first"]').inputValue()).includes('saved draft'));await shot('390-writing-task');
await go('records');check('backup buttons precede long records',await p.locator('.backup-box').evaluate(n=>n.getBoundingClientRect().top<500));const download=p.waitForEvent('download');await p.locator('#records [data-export=json]').click();const d=await download;const dest=path.join(__dirname,'probe-export.json');await d.saveAs(dest);const exported=JSON.parse(fs.readFileSync(dest,'utf8'));check('backup includes original answer and writing fields',exported.fields['full-test-reading-q1']==='retained-mobile-draft'&&exported.fields[id+'-first'].includes('saved draft'));fs.unlinkSync(dest);
await go('sentence-learning');await p.locator('[data-open-sentence]').first().click();check('phone popup hides bottom nav while open',await p.locator('#product-mobile-nav').isHidden());await p.locator('#sentence-source').fill('A focused practice session helps me notice details.');await p.locator('#sentence-result').fill('一段专注的练习帮助我注意细节。');await p.locator('#sentence-save').click();await p.locator('#sentence-close').click();check('sentence save and popup close preserve controls',await p.locator('#product-mobile-nav').isVisible()&&(await p.locator('#sentence-list').innerText()).includes('focused practice'));
await p.locator('#lookup-open').click();check('lookup wording no longer requires collecting',(await p.locator('#word-lookup .lookup-muted').innerText()).includes('自动进入复习'));await p.locator('#word-lookup .lookup-dictionary').click();check('lookup history link reaches vocabulary history',new URL(p.url()).hash==='#lookup-learning');
await go('vocabulary-review');const word=await p.locator('.ui-learn-term').innerText();await p.locator('.ui-word-heading h1').click();await p.keyboard.press('3');check('keyboard grades a word and advances',await p.locator('.ui-learn-term').innerText()!==word);await p.locator('#lookup-open').click();const current=await p.locator('.ui-learn-term').innerText();await p.locator('#lookup-input').fill('1');check('typing numbers in lookup does not grade words',await p.locator('.ui-learn-term').innerText()===current);await p.keyboard.press('Escape');check('escape returns focus to opener',await p.locator('#lookup-open').evaluate(n=>n===document.activeElement));
for(const width of [1440,390]){await p.setViewportSize({width,height:width===390?844:1000});for(const route of ['study','tests','writing-workbench','workspace','records','word-review','test-reading']){await go(route);if(route==='writing-workbench'){await p.locator('[data-ww-catalogue]:visible').first().click();await p.locator('#ux-writing-progress').selectOption('all')}await shot(width+'-'+route)}}
await go('guide');await p.locator('[data-ds-skill=reading]').click();await p.locator('#ds-start').click();await p.locator('#hs-rest').click();await p.waitForFunction(()=>JSON.parse(document.getElementById('daily-study-state').value).session.status==='paused');check('health pause still disables daily advance',await p.locator('#ds-next').isDisabled());await p.locator('#ds-pause').click();await p.locator('#hs-finish').click();check('no uncaught page errors',e.errors.length===0);report.pass=true;
}catch(err){report.pass=false;report.failure=err.stack;process.exitCode=1;try{await p.screenshot({path:path.join(__dirname,'failure.png'),timeout:5000})}catch{}}finally{Object.assign(report,{checks,shots});fs.writeFileSync(path.join(__dirname,live?'live-verification.json':packed?'packed-verification.json':'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,checks:checks.length,shots:shots.length},null,2));await e.close()}})().catch(e=>{console.error(e);process.exitCode=1});
