(()=>{'use strict';
const banks=[...document.querySelectorAll('.case-bank')];
function saveField(field,value){if(field.type==='checkbox')field.checked=value;else field.value=value;field.dispatchEvent(new Event('input',{bubbles:true}));}
function refresh(unit){const done=unit.querySelector('[data-case-done]').checked;unit.querySelector('.case-feedback').hidden=!done;unit.querySelectorAll('[data-case-answer]').forEach(e=>e.readOnly=done);const b=unit.querySelector('[data-case-submit]');b.disabled=done;b.textContent=done?'首答已保留':'保留作答，打开答案与精读';unit.querySelector('[data-case-status]').textContent=done?'已完成首答 · 可在下方对照证据并修订':'先作答；不确定的题也可记录判断与疑点。';unit.querySelector('[data-case-state]').textContent=done?'已作答':'未作答';const count=unit.querySelector('[data-case-wordcount]');if(count)count.textContent=(unit.querySelector('[data-case-answer]').value.trim().match(/\S+/g)||[]).length+' 词';}
banks.forEach(bank=>{
 const units=[...bank.querySelectorAll('.exam-case')],search=bank.querySelector('[data-case-search]'),mode=bank.querySelector('[data-case-filter]');let type='全部';
 function filter(){const q=search.value.trim().toLowerCase();let visible=0;for(const unit of units){const done=unit.querySelector('[data-case-done]').checked,matchType=type==='全部'||JSON.parse(unit.dataset.types).includes(type);unit.hidden=!(matchType&&(!q||unit.dataset.search.includes(q))&&(mode.value==='all'||(mode.value==='done'?done:!done)));if(!unit.hidden)visible++;}bank.querySelector('[data-case-count]').textContent=`显示 ${visible} / ${units.length} 组 · 已作答 ${units.filter(u=>u.querySelector('[data-case-done]').checked).length} 组`;bank.querySelector('[data-case-empty]').hidden=visible>0;}
 units.forEach(unit=>{refresh(unit);unit.querySelector('[data-case-submit]').addEventListener('click',()=>{const answers=[...unit.querySelectorAll('[data-case-answer]')],missing=answers.find(a=>!a.value.trim());if(missing){unit.querySelector('[data-case-status]').textContent='请先完成各题；暂时无法判断时可写“不确定”并留下理由。';missing.focus();return;}saveField(unit.querySelector('[data-case-saved-at]'),new Date().toISOString());saveField(unit.querySelector('[data-case-done]'),true);refresh(unit);if(mode.value==='new')mode.value='all';filter();unit.querySelector('.case-feedback').scrollIntoView({block:'start',behavior:'smooth'});});});
 search.addEventListener('input',filter);mode.addEventListener('change',filter);
 bank.querySelectorAll('[data-case-type]').forEach(b=>b.addEventListener('click',()=>{type=b.dataset.caseType;bank.querySelectorAll('[data-case-type]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();}));
 bank.querySelector('[data-case-next]').addEventListener('click',()=>{const next=units.find(u=>!u.hidden&&!u.querySelector('[data-case-done]').checked);if(next){next.open=true;next.scrollIntoView({behavior:'smooth',block:'start'});}else bank.querySelector('[data-case-count]').textContent='当前筛选内已全部作答，可以切换题型或查看已完成的练习。';});
 bank.addEventListener('input',e=>{if(e.target.matches('[data-case-answer]')){const count=e.target.closest('.exam-case').querySelector('[data-case-wordcount]');if(count)count.textContent=(e.target.value.trim().match(/\S+/g)||[]).length+' 词';}});
 filter();
});
function revealRoute(){const id=decodeURIComponent(location.hash.slice(1)),unit=document.getElementById(id);if(!unit?.classList.contains('exam-case'))return;const bank=unit.closest('.case-bank');bank.querySelector('[data-case-search]').value='';bank.querySelector('[data-case-filter]').value='all';bank.querySelector('[data-case-type="全部"]').click();unit.open=true;requestAnimationFrame(()=>unit.scrollIntoView({block:'start'}));}
window.addEventListener('hashchange',revealRoute);revealRoute();
})();
