from pathlib import Path
import json
from collections import Counter
ROOT=Path(__file__).resolve().parent
BOOK=Path('C:/Users/Admin1/Documents/Codex/2026-09-12/referenced-chatgpt-conversation-this-is-an/outputs/IELTS-四科学习册')
d=json.loads((ROOT/'research/vocabulary-deep-audit-20260919.json').read_text(encoding='utf8'))
patches=json.loads((ROOT/'research/approved-deep-corrections.json').read_text(encoding='utf8'))
rows=[]
for x in d['rows']:
    r={k:x[k] for k in ['id','term','topic','meaning','chunk','status','reason','source_basis','exam_exact_wordform_evidence']}
    changes=[p for p in patches if 'data-tv-id="'+x['id']+'"' in p['selector']]
    r['found_status']=r['status'];r['repairs']=[p['new'] for p in changes]
    if changes:
        for p in changes:
            r['chunk']=r['chunk'].replace(p['old'],p['new'])
        r['status']='达标';r['reason']='词义/短搭配已按原发现作局部修订；详见修订记录。完整原句依据仍存疑。'
    rows.append(r)
html='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>1000词条逐项审核</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f6ef;color:#253d32;font:15px/1.85 "Microsoft YaHei",sans-serif}main{max-width:1050px;margin:auto;padding:28px 18px 60px}h1{font-size:29px}a{color:#216f54;overflow-wrap:anywhere}p{margin:8px 0}.intro,article{padding:20px;background:white;border:1px solid #d3dcd2;border-radius:9px;margin:14px 0}.intro{border-left:4px solid #497962}nav{display:flex;flex-wrap:wrap;gap:10px;position:sticky;top:0;background:#f5f6ef;padding:12px 0}input,select,button{font:inherit;max-width:100%;padding:8px 10px;border:1px solid #becbbc;border-radius:5px;background:white}input{flex:1;min-width:160px}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}h2{font-size:20px;display:inline;margin-right:12px}.badge{display:inline-block;font-size:12px;padding:1px 7px;border-radius:4px;background:#fff2d3;color:#795d0b}.badge.good{background:#e8f2e9;color:#315e3b}.badge.bad{background:#fce4e2;color:#8e332d}.meta{font-size:13px;color:#637362}summary{cursor:pointer}#pager{display:flex;justify-content:center;gap:14px;align-items:center}.empty{padding:30px}article{overflow-wrap:anywhere}</style></head><body><main><h1>1000词条逐项审核</h1><div class="intro"><p>这里的“达标”仅指词义与短搭配首轮语言审读。全部1000条的完整真实原句依据仍为<strong>存疑</strong>，不能据此认证官方范例、雅思高分表达或总体高频。</p><p>词频栏是27篇考试文本内的精确拼写计数：TF＝出现次数；DF＝出现篇数／27。0不等于这个词从未在雅思出现；没有合并屈折变化或短语。</p><p>原首审995达标、4存疑、1不达标。已修订的5个词条保留发现时状态与具体改动；语言首审不是逐条权威词典认证。</p><a href="学习单元与词汇深审.html">学习单元完整审核 →</a></div><nav><input id="q" type="search" placeholder="搜索词语、中文义项、话题" aria-label="搜索词汇"><select id="status" aria-label="筛选语言审读状态"><option value="">全部语言首审状态</option><option>达标</option><option>存疑</option><option>不达标</option><option value="repaired">本轮已修订</option></select><select id="source" aria-label="筛选样本出现"><option value="">全部样本证据</option><option value="yes">27篇内找到精确词形</option><option value="no">27篇内未找到精确词形</option></select></nav><p id="count" role="status"></p><div id="list"></div><div id="pager"><button id="prev">上一页</button><span id="page"></span><button id="next">下一页</button></div><script type="application/json" id="rows">__DATA__</script><script>
const data=JSON.parse(document.querySelector('#rows').textContent),q=document.querySelector('#q'),status=document.querySelector('#status'),source=document.querySelector('#source');let page=0;const size=40;const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function render(reset=false){if(reset)page=0;const needle=q.value.trim().toLowerCase();const filtered=data.filter(x=>JSON.stringify([x.term,x.meaning,x.topic]).toLowerCase().includes(needle)&&(!status.value||(status.value==='repaired'?x.repairs.length:x.status===status.value))&&(!source.value||(source.value==='yes'?x.exam_exact_wordform_evidence.tf>0:!x.exam_exact_wordform_evidence.tf)));page=Math.min(page,Math.max(0,Math.ceil(filtered.length/size)-1));const shown=filtered.slice(page*size,(page+1)*size);document.querySelector('#count').textContent=`匹配 ${filtered.length} / 1000 条 · 每页 ${size} 条`;document.querySelector('#list').innerHTML=shown.map(x=>{let e=x.exam_exact_wordform_evidence,s=x.source_basis;return `<article><h2>${esc(x.term)}</h2><span class="badge ${x.status==='达标'?'good':x.status==='不达标'?'bad':''}">词义／搭配：${esc(x.status)}</span><span class="badge">完整原句：存疑</span><p>${esc(x.meaning)} · ${esc(x.chunk)}</p><p class="meta">${esc(x.topic)} · 本样本 TF ${e.tf} / DF ${e.df} ÷ 27篇</p><p>${esc(x.reason)}</p>${x.repairs.length?`<p>发现时：${esc(x.found_status)}；已修订：${x.repairs.map(esc).join('；')}</p>`:''}<details><summary>来源与范围</summary><p>${esc(s.note)}</p><a href="${esc(s.url||s.live_dictionary_link)}" target="_blank" rel="noopener">词条范围参考</a><p>来源链接支持词形或主题范围，不能证明本地搭配取自原文。精确词形证据文档：${esc((e.document_ids||[]).join('、')||'当前样本无精确匹配')}</p></details></article>`}).join('')||'<p class="empty">没有匹配词条。</p>';document.querySelector('#page').textContent=filtered.length?`${page+1} / ${Math.ceil(filtered.length/size)}`:'0 / 0';document.querySelector('#prev').disabled=page===0;document.querySelector('#next').disabled=(page+1)*size>=filtered.length}for(const n of [q,status,source])n.addEventListener('input',()=>render(true));document.querySelector('#prev').onclick=()=>{page--;render()};document.querySelector('#next').onclick=()=>{page++;render()};render();</script></main></body></html>'''
html=html.replace('__DATA__',json.dumps(rows,ensure_ascii=False).replace('<','\\u003c'))
for directory in [ROOT/'research',BOOK]:(directory/'词条逐项审核.html').write_text(html,encoding='utf8')
(ROOT/'research/vocabulary-current-rows-20260919.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf8')
print(json.dumps({'rows':len(rows),'repaired':sum(bool(r['repairs']) for r in rows),'language_status':dict(Counter(r['status'] for r in rows))},ensure_ascii=False))
