from pathlib import Path
from reviewed_text_corrections import correct_transcription
import json,re,hashlib

R=Path(__file__).parent
B=Path('C:/Users/Admin1/Documents/Codex/2026-09-12/referenced-chatgpt-conversation-this-is-an/outputs/IELTS-四科学习册')
blocks=json.loads((R/'reading-source-c21-blocks.json').read_text('utf-8'))
pdf=next(B.rglob('8ee8170c*.pdf'))
CASES=[]
TF='Do the following statements agree with the information given in the reading passage? Write TRUE, FALSE or NOT GIVEN.'
YN='Do the following statements agree with the views/claims of the writer? Write YES, NO or NOT GIVEN.'
NOTE='Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.'
MC='Choose the correct letter, A, B, C or D.'
SUM='Complete the summary using the list of words below. Write the correct letter for each answer.'
END='Complete each sentence with the correct ending, A–F, below.'
def ps(page,start,end):return blocks[str(page)][start:end]
def q(n,prompt,answer,evidence,explanation,ins=None,options=None):
 d=dict(number=n,prompt=prompt,answer=answer,evidence=evidence,explanation=explanation)
 if ins:d['instructions']=ins
 if options:d['options']=options
 return d
def write():
 d={'schemaVersion':1,'date':'2026-09-19','summary':{'cases':len(CASES),'originalPassages':len({c['source']['originalUnit'] for c in CASES}),'questions':sum(len(c['questions']) for c in CASES)},'cases':CASES}
 p=R/'authentic-reading-cambridge-cases.json';tmp=p.with_suffix('.tmp');tmp.write_text(json.dumps(d,ensure_ascii=False,indent=2),'utf-8');tmp.replace(p)
def add(id,test,passage,title,pages,qpages,paras,types,questions,intensive,context=''):
 # Correct only unambiguous OCR errors; never simplify, invent, or rephrase source content.
 clean=[s.replace('aimost','almost').replace('Pasteure//a','Pasteurella').replace('Biogas lnternational','Biogas International').replace('Vincenzo Coronel Ii','Vincenzo Coronelli') for s in paras]
 clean=[correct_transcription(s) for s in clean]
 c=dict(id=id,skill='reading',questionTypes=types,title=title,source=dict(id='c21-academic',originalUnit=f'C21 Test {test} Reading Passage {passage}',title='Cambridge IELTS 21 Academic',path=pdf.relative_to(B).as_posix(),page=pages,questionPages=qpages,answerPage=123 if test==3 else 125,test=f'Test {test} · Reading Passage {passage}',kind='真题',sha256=hashlib.sha256(pdf.read_bytes()).hexdigest()),
 paragraphs=[dict(label=f'原文片段 · {i+1}',text=s) for i,s in enumerate(clean)],questions=questions,wordCount=sum(len(s.split()) for s in clean),
 instructions='按原题号作答。保留考试原文与题目难度；以下是连续原段裁切，未改写原文。',
 contextNote=context or '数字和相对时间均保留原考试文章语境；同篇其他裁切不另计为一篇原文。',
 intensive=intensive,status='达标',verification={'originalQuestions':'对照原PDF题页','originalAnswers':'对照原PDF答案页','context':'保留所选题目的全部证据；含NOT GIVEN的题还核对了完整原文，不把裁切造成的缺信息当作NOT GIVEN。'})
 assert 2<=len(clean)<=6
 assert 180<=c['wordCount']<=570,(id,c['wordCount'])
 assert all(x['answer'] and x['evidence'] and x['explanation'] for x in questions)
 CASES.append(c);write()

add('rd-c21-t3-saiga-adaptation',3,1,'Saving the saiga · 生存适应与早期数量变化',[61],[63,64],ps(61,5,9),['note-completion','true-false-not-given'],[
 q(1,'has a large bulbous nose with swollen nostrils that keep ______ out','dust','they filter out dust','keep out把filter out改述为阻挡进入；原文dust是名词，满足一词。',NOTE),
 q(2,'lower the temperature of its ______ in summer','blood','cool the blood during hot, dry summers','lower the temperature of对应cool；被降温的是blood，不能填空气。',NOTE),
 q(3,'grows a thick ______ in winter, which it loses in spring','coat','a heavy winter coat that the saiga sheds when the weather warms up','thick对应heavy；loses对应sheds，空格是毛被coat。',NOTE),
 q(4,'poaching, especially for the ______ of male saiga','horns','Male saiga are a particular target, because their horns are highly prized','poaching目的与because后的价值原因对应；须保留复数horns。',NOTE),
 q(8,'Today, numbers of saiga are distributed evenly across four nations in Central Asia: Kazakhstan, Russia, Mongolia and Uzbekistan.','FALSE','Kazakhstan ... well over 90% of the global saiga population','四国被提到不等于平均分布。超过90%在一国直接反驳evenly。',TF),
 q(9,'For most of the 20th century, the population of saiga were falling.','FALSE','numbers steadily recovered throughout most of the 20th century','时间范围完全对应most of the 20th century，方向却是recovered而非falling。',TF),
 q(10,'Efforts to protect rhinos in Africa had a significant effect on saiga populations.','TRUE','encouraging the use of saiga horns ... as an alternative to those of rhinos. Male saiga were almost wiped out','保护犀牛的替代用角倡议→雄性赛加几乎被捕尽→种群崩溃；effect不一定是正面效果。',TF)
],{'structure':['先交代地理分布，再说明鼻子和冬毛的适应，随后转向人为威胁与保护犀牛的意外后果。','每道填空都保留动词框架：filter/cool/shed，对应题面keep out/lower/lose。'],'phrases':['confined to：活动范围受限，不等于只剩一只。','a respite：暂时的缓解；only temporary引出下一轮下降。','as an alternative to：作为替代；这里是保护措施带来的反作用。'],'sentences':['Other seasonal adaptations include a heavy winter coat that the saiga sheds when the weather warms up. → that引导定语从句修饰coat；when从句给出脱毛时间。','Poaching reached epidemic levels after ... → after引出历史上的倡议，后句再给出种群后果。']})

add('rd-c21-t3-saiga-threats',3,1,'Saving the saiga · 栖息地、疾病、气候与恢复',[61,62],[63,64],ps(61,9,10)+ps(62,1,5),['note-completion','true-false-not-given'],[
 q(5,"expansion of farms and settlements, causing reduction in the size of the saiga's ______",'habitat','loss of habitat, as a result of agricultural expansion and human settlement','causing与as a result of反向排列同一因果：扩张导致栖息地减少。',NOTE),
 q(6,'loss of access to the ______ which they use for migration','routes','Physical barriers ... can block the seasonal migration routes','阻断routes就是loss of access；答案是routes，不是作为障碍的fences。',NOTE),
 q(7,'climate change, causing the disappearance of ______ which the saiga relied on','streams','many of the smaller streams that the species normally depended on have dried up and vanished','relied on对应depended on；disappearance对应vanished。',NOTE),
 q(11,'Unpredictable fluctuations in climate are threatening the wildlife of Central Asia more than in other parts of the world.','NOT GIVEN','saiga struggle to cope with temperature extremes and unpredictable fluctuations in climate','文章说明中亚赛加受威胁，但完整原文没有与世界其他地区比较严重程度；more than缺依据。',TF),
 q(12,'The Altyn Dala Conservation Initiative was formed for the benefit of a number of different animals.','TRUE',"protect and restore Kazakhstan's ... ecosystems and the many species they support, including ... saiga",'many species包括赛加但不限于它，对应a number of different animals。',TF),
 q(13,"The Altyn Dala Conservation Initiative's recognition as a World Restoration Flagship project attracted additional international funding for the scheme.",'NOT GIVEN','In 2022 the United Nations recognised the initiative as a World Restoration Flagship project','recognition和accolade只说明获得认可；完整原文没有说明因此追加国际资金。',TF)
],{'structure':['连续原段依次处理栖息地、疾病、气候、保护项目及数量恢复，原因与应对不混写。','NOT GIVEN两题都增加了原文没有的关系：跨地区程度比较、认可导致资金增加。'],'phrases':['as a result of：后面接原因；不要将迁徙障碍当成结果。','may have triggered：推测过去可能诱发，不能改为已证实。','an accolade reserved for：特定对象才能获得的荣誉，不自带经费含义。'],'sentences':['Physical barriers such as railways, pipelines and fences can block the seasonal migration routes of this transboundary species. → such as列的是阻碍物，中心宾语是routes。','Its purpose is to protect and restore ... ecosystems and the many species they support. → they指ecosystems，而非合作机构。']},'这里包含原文后半部连续5段。两道NOT GIVEN已同时核对完整原文；不是因为裁切省略了答案。种群数和now按原考试文章时间理解。')

add('rd-c21-t3-dart-city',3,2,'Dar es Salaam · 城市扩张与交通方案',[65],[67],ps(65,5,10),['true-false-not-given'],[
 q(14,'The population of Dar es Salaam is rising more rapidly than was previously predicted.','NOT GIVEN','Its population has increased eightfold since 1980 ... United Nations projections anticipate ...','原文给历史增长和多份未来预测，没有“实际超过以前预测”的同一指标比较；不能由多个大数字推出more rapidly。',TF),
 q(15,'Most of the residents of Dar es Salaam live in high-rise blocks on the edge of the city.','FALSE','four out of five of its people live in single-storey informal settlements','four out of five支持most，但single-storey直接反驳high-rise。',TF),
 q(16,'Residents have been consulted about their views on the suburban rail line in Dar es Salaam.','NOT GIVEN','A single suburban rail line serves residents in a few areas to the south','有铁路服务不等于居民接受过意见咨询；全文未述consultation。',TF),
 q(17,'The majority of the present residential development in Dar es Salaam is unplanned.','TRUE','nearly all takes place informally without any agreed strategy','nearly all对应majority；without any agreed strategy对应unplanned。',TF),
 q(18,"Dar es Salaam's authorities have decided to follow the public transport plan adopted by a large number of African cities.",'FALSE',"Unlike many cities on the continent, Dar es Salaam isn't trying to build a metro. ... the bus.",'Unlike标示相反路径：很多城市地铁，本市公交；不是采用共同方案。',TF)
],{'structure':['人口规模→居民住处与交通困境→道路历史→无规划扩张→选择公交。','三道有判断证据的题分别看建筑层数、规划状态和unlike对照；两道NG都添加原文未谈的比较或咨询。'],'phrases':['on the periphery：城市外围。','a legacy of：留下的历史结构，不等于目前仍为殖民政府管理。','pinning its hopes on：把希望寄托于某方案。'],'sentences':['Nearly all the expansion is happening on the periphery, and nearly all takes place informally without any agreed strategy. → 并列两分句分别说位置与规划，不将二者因果化。','Unlike many cities on the continent, ... → 句首介词短语决定第18题的反向比较。']},'保留开篇连续5段。Q14和Q16的NOT GIVEN已对全文核验；并非只凭片段没有出现就判缺信息。')

add('rd-c21-t3-dart-system',3,2,'Dar es Salaam · 公交设计与实际故障',[65,66],[68],ps(65,10,11)+ps(66,1,4),['note-completion'],[
 q(19,'the buses use designated ______ to cut down on delays','lanes','bus lanes separated from other traffic ... to reduce stoppages','designated lanes对应与其他交通隔开的专用道；delays改述stoppages。',NOTE),
 q(20,'passengers pay fares before ______','boarding','Ticket purchase and control takes place at stations prior to boarding','before与prior to同义；答案boarding是付费之后发生的动作。',NOTE),
 q(21,'passengers in ______ can use every part of the system','wheelchairs','the entire route is accessible to people using wheelchairs','in wheelchairs改述using wheelchairs；题目限定乘客在什么工具中，不填baby buggies。',NOTE),
 q(22,'the temperature control is sometimes not activated in order to reduce ______ use','fuel','drivers often refuse to turn on the air conditioning to save fuel','temperature control对应air conditioning；reduce ... use对应save，保留名词fuel。',NOTE),
 q(23,'insufficient number of vehicles are available due to the effects of a severe ______','flood','A shortage of buses after a serious flood at the main depot','insufficient number对应shortage；severe对应serious；缺车原因是flood。',NOTE),
 q(24,'passengers are unable to use ______ because some equipment is out of action','smartcards',"Smartcards can't be used as the mechanical readers aren't working",'some equipment指读卡器，空格问不能使用的东西，因此填smartcards而非readers。',NOTE),
 q(25,'tickets have to be checked manually at station ______','gates','Staff stand by the gates and tear tickets as people enter','人工撕票的地点是gates；tickets在题面已给，不能重复填入。',NOTE),
 q(26,'______ frequently build up during rush hours','queues','As a result, queues are considerable at peak times','rush hours与peak times同义；人工检票造成queues，单词复数照原文。',NOTE)
],{'structure':['先说专用道、上车前买票、无台阶设计；再转向空调、洪水、设备故障；最后交代扩建阶段。','读设计优势时定位19–21，读实际问题时定位22–26，不能把未来线路建设误填为现有故障。'],'phrases':['prior to boarding：上车之前。','out of action / not working：停用或故障，而不是没有购买设备。','As a result：把人工检票和高峰长队连接起来。'],'sentences':["Smartcards can't be used as the mechanical readers aren't working either, forcing passengers to buy individual paper tickets for every journey. → as解释原因，forcing说明随后被迫采取的办法。",'Ticket purchase and control takes place at stations prior to boarding ... → prior to只管买票检票的时间，不表示下车后付费。']},'原第6–9段连续裁切，包含所有8个填空证据。路线未来阶段按文章当时的计划理解。')

endings=['A. Homo sapiens emerged at an earlier point in time than experts previously believed.','B. previous assumptions about who had power in the prehistoric world were inaccurate.','C. gender roles in extinct hominin species were different from those in Homo sapiens societies.','D. experts may have been mistaken about who looked for food in early human communities.','E. Homo sapiens was probably not the only species capable of sophisticated workmanship.','F. other species managed to survive in harsh environments before the arrival of Homo sapiens.']
add('rd-c21-t3-past-discoveries',3,3,'Rethinking the Past · 发现怎样改变既有认识',[69],[71,72],ps(69,4,7),['multiple-choice','matching-sentence-endings'],[
 q(27,'What is the writer doing in the second paragraph?','A','Two things stand out to me. One is ... advanced behaviours ... much further back ... And the other ... misunderstood gender roles','作者归纳两项认识变化，不是在罗列考古学家的争议；second paragraph指原第2段。',MC,['A. pinpointing some key changes in our understanding of prehistory','B. outlining some aspects of prehistory which are still poorly understood','C. summarising some attitudes towards recent archaeological revelations','D. giving an overview of some current disagreements among archaeologists']),
 q(31,'The findings at Kalambo Falls revealed that','E',"buried logs ... shaped with stone tools so that they interlocked ... 476,000 years old ... before our species",'石器加工并互锁的木材早于现代人，支撑其他物种也能进行复杂制作；不是说现代人提前出现。',END,endings),
 q(32,'Evidence from high-altitude regions suggests that','F','the Denisovans lived on the frozen heights ... 200,000 years ago','extinct hominins先在严寒高地生活，对应other species在Homo sapiens之前适应恶劣环境。',END,endings)
],{'structure':['开篇交代发现很多、共同线索难找；第二段明确两条总体变化；第三段以建筑和高地定居举证。','第31与32题都与旧时间线被推翻有关，但分别是加工能力和环境适应，不能看到before就选同一项。'],'phrases':['come thick and fast：接连大量出现。','as opposed to：对比修正前后的年龄估计。','upending the old notion：推翻旧看法，不是仅增加无关事实。'],'sentences':["This would be unsurprising if they weren't 476,000 years old. → 虚拟条件凸显年代是发现惊人之处。",'Two things stand out to me. One ... And the other ... → 平行结构直接给第27题的篇章功能。']},'原第1–3段连续裁切；第27题的second paragraph仍指原文第2段。句尾匹配保留A–F完整选项，不删干扰项。')

art=ps(69,7,8)+[blocks['69'][8]+' '+blocks['70'][1]]
add('rd-c21-t3-past-art',3,3,'Rethinking the Past · 艺术年代、研究争议与脑容量',[69,70],[72],art,['yes-no-not-given'],[
 q(35,"It seems likely that the Neanderthals' cave paintings were the first examples of artwork ever created.",'NO','Even earlier species, such as Homo erectus, may also have made art','Even earlier直接给出更早物种可能作画的证据，反驳尼安德特人必为最早的倾向判断。',YN),
 q(36,'It is very rare to find prehistoric artwork carved onto shells.','NOT GIVEN','may also have made art, for example by engraving patterns on shells','原文只举贝壳刻纹这一例子，全文没有very rare的频率判断。',YN),
 q(37,'The methods which the researchers used to examine the Rising Star cave system were rather unconventional.','NOT GIVEN','the way the results were released, in a non-traditional journal','non-traditional修饰发表结果的期刊，不是考察洞穴的方法；全文未评价实地研究方法是否反常。',YN),
 q(38,'It is unclear how old the etchings in the Rising Star cave system are.','YES','these have yet to be firmly dated ... more evidence is needed ... dating of the etchings','have yet to be firmly dated表示尚未可靠定年，正好支持unclear how old。',YN),
 q(39,'The means used to publicise the findings from the Rising Star cave system added to the controversy that surrounds them.','YES','The dispute has only been heightened by the way the results were released','publicise findings对应results released；added to controversy对应dispute heightened。',YN),
 q(40,'The size of H. naledi brains is a key factor in the question of whether these hominins were able to produce art.','NO',"I think the species' small brains are a distraction ... internal wiring ... equally important",'该题问作者观点，不是前人dogma。作者明确把小脑容量称为干扰焦点，不能把先引述的旧教条当作者结论。',YN)
],{'structure':['先列更早艺术线索，再提出H. naledi的争议；后段区分证据仍不足与脑容量不应主导判断。','两道NG分别扩大为频率、把发表方式偷换成研究方法；两者都不是看漏关键词。'],'phrases':['have yet to be firmly dated：定年仍未充分确认。','understate the situation：说得太轻，强调争议强烈。','a distraction：使注意力偏离关键问题的因素。'],'sentences':['However, it had quite a small brain ... and was therefore, according to palaeoanthropological dogma, incapable of complex behaviours. → according to注明这是旧教条的推论。','But other properties, such as the brain’s internal wiring, are surely equally important ... → But引出作者对只看尺寸的修正，问观点必须跟到这里。']},'保留原第4–5段；第5段跨PDF69–70页已按原句接合，不增删论证。NG已核对整篇文章。')

add('rd-c21-t3-past-preconceptions',3,3,'Rethinking the Past · 渐进变化与性别预设',[70],[71,72],ps(70,2,6),['multiple-choice','matching-sentence-endings'],[
 q(28,'In the sixth paragraph, the writer mentions mobile phones to make the point that','A','Evolution usually works by incremental steps and so does technology.','手机比喻说明技术和进化多为逐步发展；并非评价当代手机好坏。',MC,['A. most developments happen in a gradual way.','B. innovation can come from a variety of sources.','C. not all technological advancements are positive.','D. the path of evolution can often be unpredictable.']),
 q(29,"In the seventh paragraph, the phrase 'unpick this stuff' refers to the task of",'D',"Archaeology was invented by individuals with ... patriarchal views ... those notions fed into their research. Today's researchers are trying to unpick this stuff",'this stuff回指旧父权观念渗入研究，需要重新评估受这些观念影响的研究；不是指证据造假。',MC,['A. assessing the impact of certain recent research findings.','B. questioning the authenticity of evidence used in earlier research.','C. conducting research into how prehistoric societies were organised.','D. reevaluating research influenced by outdated beliefs about society.']),
 q(30,'What does the writer suggest in the final paragraph?','A',"Inequality, authoritarianism and patriarchy aren't inevitable. They're choices, and prehistory shows us that we can choose differently.",'考察史前社会揭示当代制度并非必然，支持我们选择更公平社会。作者不是仅说仍有未知。',MC,['A. Studying past societies could help us create a fairer society today.','B. We should not judge past societies by the standards of modern society.','C. We still have much to learn about how societies have evolved over history.','D. There is more than one way to interpret evidence about societies in prehistoric times.']),
 q(33,'An academic publication from June 2023 shows that','D','a meta-analysis published in June 2023 ... found women hunted in 80 per cent of them','新汇总反驳男性负责狩猎的旧假定；D谁找食物，B谁掌权不能互换。',END,endings),
 q(34,'Analysis of a 4000-year-old Iberian leader indicates that','B','an Iberian leader ... turned out to be female, not male as many had assumed','牙齿蛋白分析推翻领导者为男性的假设，对应谁有权力的旧看法不准确。',END,endings)
],{'structure':['以科技类比解释渐进变化，再把“预设妨碍证据”转到性别研究，最后联系今天的选择。','第33题是狩猎者，第34题是统治者；相似的gender主题不能代替对象核对。'],'phrases':['incremental steps：逐步累积，直接支撑第28题A。','get in the way of：妨碍；不是“为……提供途径”。','in line with this：引入与前项结果一致的新证据。'],'sentences':["The idea that there was a sudden explosion ... isn't inherently ridiculous ... But there was never that much evidence ... → 先承认可能性，再说证据不足，不能只抓第一半句。",'an Iberian leader ... turned out to be female, not male as many had assumed → as从句标出被推翻的是此前假设。']},'原第6–9段连续裁切；题面sixth/seventh/final paragraph分别对应本片段第1/2/4段。匹配题完整保留A–F。')

add('rd-c21-t4-hyacinth-problem',4,1,'Water hyacinth · 入侵植物与能源问题',[82],[84],ps(82,6,10),['true-false-not-given'],[
 q(1,'Water hyacinth was introduced as a decorative plant in east Africa.','TRUE','Belgian colonists in Rwanda, who liked the look of its glossy leaves and delicate purple flowers floating in their ponds','liked the look与自家池塘花叶说明最初作装饰用途。',TF),
 q(2,'Fishermen took some water hyacinth plants to Lake Victoria.','FALSE',"it had 'escaped' out of the country via the Kagera river and made its way downstream to Lake Victoria",'实际传播路径是河流顺流而下，不是渔民运送。',TF),
 q(3,'It is now difficult to force boats through the thick water hyacinth on Lake Victoria.','TRUE','the boats ... struggle to navigate through the mass of plants','struggle to navigate对应difficult to force boats through。',TF),
 q(4,'Chemicals produced by the water hyacinth plants are affecting the numbers of fish in Lake Victoria.','NOT GIVEN','blocking fishing routes and providing a new habitat for disease-carrying mosquitoes','文中说堵住捕鱼线路并供蚊子栖息，没有说植物产生化学物质影响鱼数；渔获难运不等于鱼类减少。',TF),
 q(5,"Cooking with charcoal has been proved to be even worse for people's health than cooking with wood.",'NOT GIVEN','About three out of four families in Kenya depend on wood or charcoal ... Using solid fuels like these ... increases indoor pollution','原文并列木材与木炭作为有害固体燃料，但全文没有健康危害高低比较。',TF),
 q(6,'People found it impossible to remove much water hyacinth from Lake Victoria.','FALSE','huge piles of water hyacinth that villagers had taken out of the water ... were a common sight','huge piles与taken out说明已移除大量植物，直接反驳impossible to remove much。',TF),
 q(7,'Scientists started investigating the possibility of using water hyacinth to generate biogas in the last century.','TRUE','since as early as the 1980s ... began to explore its potential as a biofuel','1980s属于20世纪；题面last century对应原文年代，不要求你查当今研究。',TF)
],{'structure':['植物起源与传播→妨碍捕鱼→烟熏和采柴压力→清除后作为燃料的潜力。','分清四组容易偷换的对象：自然河流/渔民，运鱼困难/鱼数量，燃料共有风险/风险谁更大，未能根除/不能移除任何大量植物。'],'phrases':['made its way downstream：沿水流向下游传播。','struggle to navigate：难以航行，而不是彻底没有船。','potential as a biofuel：作为生物燃料的可能性，区别已投入使用。'],'sentences':["But buried in those decaying waxy leaves was a renewable energy gold mine. → 倒装句突出被当废物的叶片中存在能源潜力；gold mine是比喻。",'Using solid fuels like these for cooking increases indoor pollution. → like these回指木材木炭的共同类别，不给两者排序。']},'开篇连续4段保留完整因果背景；两道NG另核对了全文，没有把片段未出现的内容当答案。健康数值只作为原考试文章陈述理解。')

FLOW='Complete the flow-chart below. Choose NO MORE THAN TWO WORDS from the passage for each answer. Generating biogas for domestic use in Dunga.'
add('rd-c21-t4-hyacinth-biogas',4,1,'Water hyacinth · 沼气流程、收益与价格障碍',[83],[85],ps(83,2,7),['flow-chart-completion','note-completion'],[
 q(8,'First, place water hyacinth together with some ______ into a digester','cow dung','a mix of water hyacinth and cow dung into biogas for cooking','本村digester混入cow dung，两词；不能因前文另有chicken manure实验就换材料。',FLOW),
 q(9,'Leave the mixture until the ______ is completed','fermentation / fermentation process','over the next 20 to 30 days, it goes through a fermentation process and breaks down','题面until ... completed对应经过发酵阶段；官方答案接受fermentation或fermentation process，均不超过两词。',FLOW),
 q(10,'Capture the gas emitted by the digester and use ______ to transport it to individual homes','pipes','the clean burning gas is passed through pipes to the point of use','填运送管道pipes，不填终点homes或燃气本身。流程终点还包括做饭和净水。',FLOW),
 q(11,'no need for them to spend so much ______ collecting fuel','time',"they don't have to devote a lot of time every day to gathering firewood",'spend ... collecting与devote ... to gathering对应；空格是节省的time。',NOTE),
 q(12,'they can focus on different tasks that bring in ______','money',"they're able to make more money for their families from other enterprises",'different tasks对应other enterprises；bring in对应make money。',NOTE),
 q(13,'the ______ of the digesters is beyond the reach of most villages','price',"unless the price of the machines drops ... most communities will never be able to afford any",'beyond the reach意为负担不起，与unless price drops的条件对应；题目一词，不能填750 dollars。',NOTE)
],{'structure':['村庄引入设备→混合发酵与输气→女性时间收入和健康收益→仍待研究及价格限制。','流程图按原箭头First→Leave→Capture→Use填写，收益/障碍笔记另按段意定位。'],'phrases':['a two-for-one solution：同时应对水草与柴火依赖。','breaks down, giving off gas：分解并释放气体。','beyond the reach：难以负担，在本题是价格而非地理距离。'],'sentences':['The mixture goes in one end ... and ... goes through a fermentation process and breaks down, giving off gas ... → 主干依次说明进入、发酵、分解；giving off补充结果。',"But unless the price of the machines drops ... most communities will never be able to afford any. → unless提出普及的必要条件，不能把目前局部成功扩成处处买得起。"]},'原第6–10段连续裁切。原流程最后一步为“Then use the gas for cooking as well as making water fit for human consumption”，与片段purifying water对应，未另造步骤。')

delhi_options=['A. basic outlook','B. employment opportunities','C. wealthy visitors','D. distant country','E. primary objective','F. similar advantages','G. thriving economy','H. nearby district','I. dense population','J. new immigrants']
add('rd-c21-t4-multilingual-background',4,2,'Multilingualism · 迁移背景与研究目标',[86],[88],ps(86,5,9),['summary-completion-options','yes-no-not-given'],[
 q(14,'The city of Delhi has a ______ and as you walk through its streets you hear people speaking a variety of languages.','I','The crowded and bustling streets of Delhi teem with life ... more than 20 million people','crowded与2000多万人对应dense population；不是只因bustling就选thriving economy。',SUM,delhi_options),
 q(15,'Some of them have spent their entire life in Delhi, while others are ______.','J','many millions more have recently made India’s capital their home, having moved from ...','recently迁入与new immigrants对应；不等于wealthy visitors短期游客。',SUM,delhi_options),
 q(16,'Whether they have come from a ______ or have travelled from the other side of India,','H','having moved from surrounding neighbourhoods, cities and states or across the country','surrounding neighbourhoods对应nearby district，与other side形成近/远对照；原文不是移自国外。',SUM,delhi_options),
 q(17,'they have all come in search of things such as improved ______.','B','often in the hope of gaining better jobs and a better life','better jobs对应employment opportunities；不要凭“更好生活”添富游客身份。',SUM,delhi_options),
 q(18,'The ______ of the research is to discover why multilingual Indian schoolchildren do not experience','E','The overriding aim of the four-year project ... is to find out why','overriding aim同义于primary objective，句法也需要单数研究目标。',SUM,delhi_options),
 q(19,'______ to those that multilingual schoolchildren in Europe experience.','F','the many benefits ... observed in schools in Europe ... do not apply to many of India’s schoolchildren','benefits对应advantages；研究问为何并未获得相似收益。',SUM,delhi_options),
 q(20,'Ten-year-old Indian schoolchildren tend to perform better in literacy tests than in numeracy tests.','NO','over 50% ... cannot read ... and just under 50% ... cannot solve ... subtraction','识字不达标超过50%，计算不达标略低于50%，方向与better in literacy相反；比较的是不能完成的比例。',YN),
 q(21,'Tsimpli had problems convincing some female students to take part in the study.','NOT GIVEN','low educational achievement ... dropping out of school ... disproportionately affecting female students','女生受退学影响更多不是难以说服参加研究；全文没有recruitment问题。',YN),
 q(22,'Tsimpli and her team wanted to know if there is a connection between poor academic performance and being taught in an unfamiliar language.','YES','investigating whether these low learning outcomes could be caused by ... language ... taught in often differs from ... used at home','研究的问题正是低学习表现与教学/家庭语言不一致是否有关。',YN)
],{'structure':['人口迁移造成多语环境→项目目标→学习表现数据→研究教学语言与家庭语言之间的落差。','摘要选词看同义替换也看搭配：primary objective of the research、similar advantages to those。'],'phrases':['the overriding aim：首要目标。','let alone：更不用说，用来递进语言数量。','disproportionately affecting：影响不成比例，不自动说明调查招募困难。'],'sentences':['over 50% ... cannot read ... and just under 50% ... cannot solve ... → 两个否定能力比例并列，解第20题须把“不能”保留。','Tsimpli and her colleagues are investigating whether ... → whether引导研究的问题，不能把尚在研究的假说说成已经证明的原因。']},'原第1–4段连续裁切；词表A–J保留原题所有选项，含OCR漏掉的I已按原选项和答案页恢复。NG21已核对完整文章。')

add('rd-c21-t4-multilingual-findings',4,2,'Multilingualism · 教学语言与出人意料的结果',[87],[88,89],ps(87,1,5),['yes-no-not-given','multiple-choice'],[
 q(23,'The researchers have decided against investigating the impact teaching methodology may have on learning outcomes.','NO','They intend to look not only at test results, but also ... the teaching practices themselves','intend to investigate practices直接反驳decided against investigating methodology。',YN),
 q(24,'What point does the writer make about primary schools in India in the sixth paragraph?','C','English, may hold back those children who have little familiarity with, or exposure to, the language','不熟悉教学用英语可能进一步拖住贫困儿童；不是说动机能使英语更容易学。',MC,['A. Exposure to English outside of school is of limited benefit.','B. Children learn English more easily when they are well motivated.','C. Poor children may be disadvantaged further by being instructed in English.','D. There is little consistency across schools with regard to instruction in English.']),
 q(25,"What is Tsimpli suggesting when she uses the phrase 'that ship has sailed'?",'D',"We are not suggesting that English be withdrawn - that ship has sailed",'紧贴前半句be withdrawn理解：完全撤回英语已不现实。B是后文改进方向，却不是该习语所指。',MC,['A. The findings of the report may be of little help to some Indian schoolchildren.','B. Instruction in English could be better adapted to the needs of schoolchildren.','C. Schools have had limited success in teaching English as a separate subject.','D. It is too late to remove English completely as a language of instruction in schools.']),
 q(26,'In the eighth paragraph, what do we learn has surprised researchers?','D','an unanticipated finding ... children from slum backgrounds do not seem to lag behind ... and in some cases outperform them','unanticipated锁定意外发现：贫民窟儿童读写算并未落后，有时更好；general intelligence相同只是前面的背景。',MC,['A. Boys and girls from low socio-economic groups have similar general intelligence levels.','B. The age at which children move into a slum does not affect their academic performance.','C. Slum children and children from other urban poor backgrounds have similar life experiences.','D. The literacy and numeracy skills of slum children are not lower than those of children from other urban poor backgrounds.'])
],{'structure':['准备复测并查教学方法→英语媒介潜在阻碍→调整建议→贫民窟儿童技能的意外结果。','第24题看研究发现，第25题限定习语所指，第26题用unanticipated定位“惊讶”而非所有被提及事实。'],'phrases':['the medium of instruction：教其他科目所用语言，区别作为一门语言课。','that ship has sailed：相关机会已经过去，不宜按船的字面理解。','lag behind / outperform：落后于/表现胜过，注意not与in some cases。'],'sentences':['English can still be used, but perhaps not as the medium of instruction ... It could ... be one of the subjects ... → 不是取消英语，而是区分教学媒介与课程科目。','While the preliminary results show ... an unanticipated finding has been ... → While从句提供对照背景，主句才是第26题问的意外发现。']},'原第5–8段连续裁切；题面sixth/eighth paragraph分别对应本片段第2/4段。保留may、might、preliminary等不确定表达。')

globe_options=['A. educational use','B. rare materials','C. inferior makes','D. product exchange','E. necessary skills','F. international markets','G. challenging task','H. memorable object','I. internet purchase','J. numerous problems']
add('rd-c21-t4-globe-search',4,3,'The Globemakers · 从生日礼物到制作难题',[90],[92,93],ps(90,6,10),['summary-completion-options','yes-no-not-given'],[
 q(27,"Peter Bellerby's plan to give his father a globe for his birthday was an unexpectedly ______",'G','What seemed simple enough ... an almost obsessive, decade-long journey ... a series of obstacles','本以为简单，实际历时多年且障碍多，对应challenging task。',SUM,globe_options),
 q(28,'for which he had to overcome ______.','J','marked by a series of obstacles that would have deterred anyone less determined','a series of obstacles对应numerous problems，不能把耗时本身填成物品。',SUM,globe_options),
 q(29,'He soon learnt that a straightforward ______ would not be possible.','I','not simply a matter of a quick online order','quick online order对应internet purchase，词表I不能因OCR漏字母而漏选项。',SUM,globe_options),
 q(30,'Some ______ that had been intended for','C','shoddy commercial versions designed for school classrooms','shoddy与inferior同义，versions是产品makes。',SUM,globe_options),
 q(31,'______ were available, as were some expensive antique globes, but these were beyond his budget.','A','designed for school classrooms','school classrooms对应educational use；A说使用目的而不是材料。',SUM,globe_options),
 q(32,'He even travelled to places where people might still have the ______, but Bellerby could not find what he wanted.','E','where surely the knowledge of artisan cartographers had been preserved, drew a blank','工匠知识的保存对应necessary skills；drew a blank说明找寻无结果。',SUM,globe_options),
 q(33,'The assumption today that people in the past knew very little about geography is correct.','NO',"contrary to stubbornly held popular views of our ancestors' geographical ignorance, we have known that the world is spherical ...",'contrary to明确否定流行的“祖先地理无知”假定。',YN),
 q(34,'Plato was criticised for saying the world was shaped like a leather ball.','NOT GIVEN','Plato in his work Phaedo likened it to a leather ball','只记载柏拉图比喻，没有别人批评这一观点的信息；全文也未给反应。',YN),
 q(35,'The globe made by Crates of Mallus was an accurate representation of the known world.','NOT GIVEN','the accolade of producing the first recorded globe goes to ... Crates of Mallus','first recorded说明最早记载，不评价精确度accurate；不能从奖誉推导准确。',YN),
 q(36,'Bellerby assumed he would have few problems locating a well-made globe.','YES',"Surely, Bellerby reasoned, a good-quality globe wouldn't be difficult to find",'would not be difficult直接对应few problems；实际后来遇到困难不改变起初假设。',YN)
],{'structure':['买礼物的起因→历史知识使他以为容易买→实地与市场寻觅失败→决定亲自制作并遭遇形状问题。','观点判断分别检验作者否定、未给评价、人物起初看法；不要把最终失败倒推为最初就预料到了。'],'phrases':['drew a blank：一无所获，不是画空白地图。','not one to be easily thwarted：不是轻易被阻碍的人。','oblate：两极略扁；文中解释不是完美球体。'],'sentences':["What seemed simple enough to start with triggered ... a journey ... → What从句作主语，突出预期和实际的反差。",'contrary to stubbornly held popular views ... → contrary to标示作者与流行看法相反，直接决定第33题。']},'开篇原第1–4段连续裁切，保留A–J完整词表。NG34/35已核对整篇，原文并未给柏拉图所受批评或最早地球仪的准确性评价。')

add('rd-c21-t4-globe-craft',4,3,'The Globemakers · 制作细节、历史匠人与书评判断',[91],[94],ps(91,1,5),['multiple-choice'],[
 q(37,'When Bellerby had to attach the gores to the globe surface,','B','Right at the end of the process, he learnt that the paper had stretched slightly and so the final one overlapped the first','直到最后才发现纸张拉伸产生重叠，是unexpected issue；原文未说他为此差点放弃。',MC,['A. he decided it was best to work quickly.','B. he became aware of an unexpected issue.','C. he was worried about the quality of his materials.','D. he nearly gave up the whole project.']),
 q(38,'The reviewer mentions other globe makers of the past because','C','found a kindred spirit in Martin Behaim ... Bellerby’s unflinching ambition is reflected in ... Vincenzo Coronelli','kindred spirit和ambition reflected都强调共同点，不证明他受二人启发才开始。',MC,['A. Bellerby was particularly inspired by them.','B. their achievements are not widely known.','C. Bellerby had something in common with each of them.','D. their difficulties could have been avoided.']),
 q(39,'What point is made about Bellerby in the seventh paragraph?','D','Bellerby’s book is also a lament for the fading away of centuries-old traditions ... many ... retired or passed away','lament与fading away强调惋惜技能流失；不是证明他一直有长期合作人脉。',MC,['A. He had long working relationships with numerous craftsmen.','B. He understands the lack of interest in traditional crafts.','C. He appreciates the importance of careful planning.','D. He regrets the loss of many globe-making skills.']),
 q(40,"What does the reviewer say about Bellerby's book in the final paragraph?",'A','His book ... is hardly a blueprint for commercial success','hardly是否定；blueprint指可照着做的指南。因此书不教如何创造盈利生意，下一句赞赏不取消这一判断。',MC,['A. It does not tell you how to create a profitable business.','B. It overlooks some important mapmakers.','C. It fails to discuss the future of globe-making.','D. It does not give enough details about individual customers.'])
],{'structure':['制作过程的意外细节→与两位历史匠人的共同点→传统技能消逝→评价书的价值与局限。','四题沿原段顺序各取主论点；每题保留完整四选项，不能只看glue、materials等局部词。'],'phrases':['did the trick：成功解决问题，具体指空气压缩机帮助脱模。','a kindred spirit：志趣相近者；不等于直接师承。','hardly a blueprint：几乎不能算指南，hardly不是程度加强。'],'sentences':['Although a celebration ... Bellerby’s book is also a lament ... → Although承认复兴的一面，主句强调惋惜消逝，决定第39题。','But it is more than enough to stir up admiration ... → 书缺乏商业操作指南，但仍能唤起对工艺和毅力的敬意，褒贬可并存。']},'原第5–8段连续裁切，共543词。为保留从工艺意外到最终书评的完整论证，未在段中截断；仍仅为原篇后半。题面seventh paragraph对应本片段第3段。')

print(json.dumps({'cases':len(CASES),'questions':sum(len(c['questions']) for c in CASES)},ensure_ascii=False))
