/* Isolated browser contexts only: never connects to a personal browser profile. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Admin1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT=__dirname,QA=path.join(ROOT,'daily-study-qa'),report=JSON.parse(fs.readFileSync(path.join(QA,'integration.json'),'utf8'));
const BOOK=path.dirname(report.live.source),ORIGIN='http://127.0.0.1:41749',main=fs.readFileSync(report.live.target),nav=fs.readFileSync(report.navigation.target);
const results=[],errors=[];
const mime={'.html':'text/html; charset=utf-8','.json':'application/json','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.mp3':'audio/mpeg','.wav':'audio/wav','.pdf':'application/pdf'};
async function mainQA(){
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const contexts=[];
 async function pageFor(file='book.html',viewport={width:1440,height:1080}){
  const c=await browser.newContext({viewport});contexts.push(c);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));
  await p.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!==ORIGIN)return route.abort();
    if(url.pathname==='/book.html'||url.pathname==='/navigation.html')return route.fulfill({status:200,contentType:mime['.html'],body:url.pathname==='/book.html'?main:nav});
    const rel=decodeURIComponent(url.pathname).slice(1);const roots=file==='navigation.html'?[path.dirname(report.navigation.source),BOOK]:[BOOK];
    for(const base of roots){const f=path.resolve(base,rel);if(f.startsWith(path.resolve(base)+path.sep)&&fs.existsSync(f)&&fs.statSync(f).isFile())return route.fulfill({status:200,contentType:mime[path.extname(f)]||'application/octet-stream',body:fs.readFileSync(f)});}
    return route.fulfill({status:404,body:'Not found'});
  });
  await p.goto(ORIGIN+'/'+file,{waitUntil:'load'});await p.locator('#ds-skills button').first().waitFor();return p;
 }
 async function check(name,f){try{await f();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.stack});console.log('FAIL',name,e.message);}}
 const state=async p=>p.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('ielts-finished-book-v1')).fields['daily-study-state']));
 const home=async p=>{await p.evaluate(()=>location.hash='guide');await p.locator('#ds-start').waitFor({state:'visible'});};
 const p=await pageFor();
 await check('default plan is actionable, thirty minutes and four real steps',async()=>{assert.equal(await p.locator('#ds-plan-total').innerText(),'约 30 分钟');assert.equal(await p.locator('#ds-steps li').count(),4);assert.equal(await p.locator('[data-ds-minutes="30"]').getAttribute('aria-pressed'),'true');assert(await p.locator('#ds-start').isEnabled());await p.screenshot({path:path.join(QA,'desktop-home.png')});});
 await check('multi-select updates plan and respects time budget without omitting chosen subjects',async()=>{await p.locator('[data-ds-skill="listening"]').click();await p.locator('[data-ds-skill="reading"]').click();assert.equal(await p.locator('#ds-steps li').count(),2);assert(await p.locator('[data-ds-skill="speaking"]').isDisabled());assert.equal((await state(p)).preferences.skills.length,2);await p.locator('[data-ds-minutes="15"]').click();assert.equal((await state(p)).preferences.skills.length,1);assert((await p.locator('#ds-message').innerText()).includes('保留前 1'));});
 await check('deselecting last subject restores automatic mode and writing subtype lives under writing',async()=>{await p.locator('[data-ds-skill="listening"]').click();assert.equal(await p.locator('[data-ds-skill="auto"]').getAttribute('aria-pressed'),'true');await p.locator('[data-ds-skill="writing"]').click();await p.locator('[data-ds-writing="writing1"]').click();assert.deepEqual((await state(p)).preferences.skills,['writing1']);assert((await p.locator('#ds-steps').innerText()).includes('再练一次'));});
 await check('start opens real material and makes step instructions visible',async()=>{await p.locator('[data-ds-skill="auto"]').click();await p.locator('[data-ds-skill="reading"]').click();await p.locator('#ds-start').click();await p.locator('#daily-study-dock').waitFor({state:'visible'});assert.equal(new URL(p.url()).hash,'#reading-case-rd-c21-ai-1');assert(await p.locator('#reading-case-rd-c21-ai-1').isVisible());assert.equal((await state(p)).session.index,0);});
 await check('optional notes save without requiring any exercise response',async()=>{await p.getByRole('button',{name:'随手记',exact:true}).click();await p.locator('#ds-note').fill('隔离测试：核对作者态度');await p.getByRole('button',{name:'保存笔记',exact:true}).click();assert.equal((await state(p)).session.note,'隔离测试：核对作者态度');});
 await check('moving to next step persists index and reload resumes paused without off-screen time',async()=>{await p.locator('#ds-next').click();assert.equal((await state(p)).session.index,1);await p.reload();await p.locator('#ds-pause').waitFor({state:'visible'});assert.equal(await p.locator('#ds-pause').innerText(),'继续');await home(p);assert((await p.locator('#ds-start').innerText()).includes('继续'));await p.locator('#ds-start').click();assert.equal((await state(p)).session.index,1);assert.equal((await state(p)).session.status,'active');});
 await check('pause saves progress and time stops, resume preserves current step',async()=>{await p.locator('#ds-pause').click();const before=await state(p);await p.waitForTimeout(1200);assert.equal((await state(p)).session.elapsedMs,before.session.elapsedMs);assert(await p.locator('#ds-next').isDisabled());await p.locator('#ds-pause').click();assert.equal((await state(p)).session.index,1);});
 await check('completing four self-confirmed steps archives real progress and feedback affects auto plan',async()=>{await p.locator('#ds-next').click();await p.locator('#ds-next').click();await p.locator('#ds-next').click();await p.locator('#ds-completed').waitFor({state:'visible'});assert.equal((await state(p)).session.status,'completed');assert.equal((await state(p)).history.length,1);await p.locator('[data-ds-feedback="retry"]').click();await p.locator('[data-ds-skill="auto"]').click();assert((await p.locator('#ds-plan-reason').innerText()).includes('阅读'));assert((await p.locator('#ds-plan-reason').innerText()).includes('还想再练'));});
 await check('early end keeps completed steps and allows a new subject without erasing answers',async()=>{await p.locator('#ds-start').click();await p.locator('#ds-next').click();await home(p);await p.locator('#ds-end').click();assert.equal((await state(p)).session.status,'ended');assert.equal((await state(p)).session.completed.length,1);await p.locator('[data-ds-skill="speaking"]').click();await p.locator('#ds-start').click();assert.equal((await state(p)).session.skills[0],'speaking');assert.equal((await state(p)).history.length,2);});
 await check('failed persistence never advances or leaks a pending advance into the original save controller',async()=>{const before=await state(p);await p.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('synthetic quota error');};});await p.locator('#ds-next').click();assert.equal((await state(p)).session.index,before.session.index);assert((await p.locator('#daily-study-dock .ds-message').innerText()).includes('保存未成功'));await p.evaluate(()=>{Storage.prototype.setItem=window.originalSet;const f=document.querySelector('[data-save="pr-speaking-p2-record-note"]');f.value='isolated save test';f.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal((await state(p)).session.index,before.session.index);});
 const mobile=await pageFor('book.html',{width:390,height:844});
 await check('phone layout has no overflow and start scrolls directly to the selected exercise',async()=>{assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert(await mobile.locator('#ds-start').isVisible());for(const s of ['[data-ds-minutes="15"]','[data-ds-skill="listening"]']){const box=await mobile.locator(s).boundingBox();assert(box.height>=40);}await mobile.screenshot({path:path.join(QA,'mobile-home.png'),fullPage:true});await mobile.locator('#ds-start').click();await mobile.locator('#daily-study-dock').waitFor({state:'visible'});await mobile.waitForFunction(()=>{const r=document.querySelector('#pr-listening-p2').getBoundingClientRect();return r.top>=0&&r.top<200;});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mobile.screenshot({path:path.join(QA,'mobile-session.png')});});
 const n=await pageFor('navigation.html');
 await check('new navigation candidate retains four primary entries and the daily start works',async()=>{assert.deepEqual(await n.locator('#workspace-navigation nav [data-go]').allTextContents(),['学习','练习','测试','工作区']);await n.locator('[data-ds-skill="vocabulary"]').click();await n.locator('#ds-start').click();assert(await n.locator('#prereq-vocabulary-usage').isVisible());assert(await n.locator('#daily-study-dock').isVisible());await n.screenshot({path:path.join(QA,'navigation-session.png')});});
 const broken=await pageFor();
 await check('long session cannot skip original first-answer requirement to enter hidden feedback',async()=>{await home(p);await p.locator('#ds-end').click();await p.locator('[data-ds-minutes="60"]').click();await p.locator('[data-ds-skill="auto"]').click();await p.locator('[data-ds-skill="listening"]').click();await p.locator('#ds-start').click();await p.locator('#ds-next').click();await p.locator('#ds-next').click();assert.equal((await state(p)).session.index,1);assert((await p.locator('#daily-study-dock .ds-message').innerText()).includes('保存首次作答'));await p.locator('[data-save="listening-q1"]').fill('isolated test');await p.locator('[data-freeze="listening"]').click();await p.locator('#ds-next').click();assert.equal((await state(p)).session.index,2);assert(await p.locator('#listening-feedback').isVisible());});
 await check('short writing opens the independent micro task without revealing its answer',async()=>{await home(n);await n.locator('#ds-end').click();await n.locator('[data-ds-minutes="15"]').click();await n.locator('[data-ds-skill="auto"]').click();await n.locator('[data-ds-skill="writing"]').click();await n.locator('#ds-start').click();await n.locator('#ds-next').click();const micro=n.locator('[data-save="pr-writing2-tourism-another"]');await micro.waitFor({state:'visible'});await n.waitForFunction(()=>{const r=document.querySelector('[data-save="pr-writing2-tourism-another"]').closest('details').getBoundingClientRect(),dock=document.querySelector('#daily-study-dock').getBoundingClientRect();return r.top>=60&&r.top+100<dock.top;});const openAnswers=await micro.evaluate(e=>[...e.closest('details').querySelectorAll('[data-answer-gate]')].some(d=>d.open));assert.equal(openAnswers,false);await n.screenshot({path:path.join(QA,'writing-micro.png')});});
 await check('damaged daily record is preserved and cannot be silently overwritten',async()=>{await broken.evaluate(()=>localStorage.setItem('ielts-finished-book-v1',JSON.stringify({version:1,fields:{'daily-study-state':'{broken'},snapshots:{}})));await broken.reload();await broken.locator('#ds-message').waitFor({state:'visible'});assert(await broken.locator('#ds-start').isDisabled());assert.equal(await broken.evaluate(()=>JSON.parse(localStorage.getItem('ielts-finished-book-v1')).fields['daily-study-state']),'{broken');});
 await check('requesting another subject after a manual selection actually returns to automatic planning',async()=>{await n.locator('#ds-next').click();await n.locator('#ds-next').click();await n.locator('#ds-next').click();await n.locator('[data-ds-feedback="okay"]').click();assert.deepEqual((await state(n)).preferences.skills,[]);assert.equal(await n.locator('[data-ds-skill="auto"]').getAttribute('aria-pressed'),'true');assert(!(await n.locator('#ds-plan-reason').innerText()).startsWith('写作'));});
 await check('no browser runtime errors from either integrated page',async()=>assert.deepEqual(errors,[]));
 for(const c of contexts)await c.close();await browser.close();
 const out={sourceSHA256:crypto.createHash('sha256').update(main).digest('hex'),navigationSHA256:crypto.createHash('sha256').update(nav).digest('hex'),browser:'isolated headless Edge contexts; no personal browser data',passed:results.filter(r=>r.pass).length,total:results.length,results,errors};
 fs.writeFileSync(path.join(QA,'browser-results.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({passed:out.passed,total:out.total}));if(out.passed!==out.total)process.exitCode=1;
}
mainQA().catch(e=>{console.error(e);process.exitCode=1;});
