/* Runs only a tiny synthetic fixture, never the actual learner book or browser. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {parseHTML}=require('D:/IELTS-Work/learning-adjust-20260920/synthetic-tests/node_modules/linkedom');
const M=require('./learning-adjust-model.js');
const OUT='D:/IELTS-Work/learning-adjust-20260920';
const fixtureData={skills:{reading:'阅读',writing2:'写作'},units:[{id:'lesson-one',mode:'study',skill:'reading',skillLabel:'阅读',topic:'教育',title:'合成讲解',steps:[{kind:'check',key:'read-one'}]},{id:'practice-one',mode:'practice',skill:'reading',skillLabel:'阅读',topic:'教育',title:'合成练习',steps:[{kind:'answer',key:'q-one'}]}],projects:[{id:'synthetic-project',units:['lesson-one','practice-one']}],tests:Object.fromEntries(['listening','reading','writing','speaking'].map(id=>[id,{label:id,minutes:10,...(['listening','reading'].includes(id)?{key:{'1':['right']}}:{})}]))};
function boot(seed,failWrite=false,navigationVersion=0){
 const store={value:seed||{version:1,fields:{},snapshots:{}},failWrite};
 const localData=JSON.parse(JSON.stringify(fixtureData));if(navigationVersion)localData.navigationVersion=navigationVersion;
 const filters=mode=>`<section class="panel" id="${mode}"><header class="la-heading"><h1>${mode}</h1></header><nav id="la-${mode}-location"></nav><div class="la-toolbar"><label>科目<select id="la-${mode}-skill"><option value=""></option><option value="reading">阅读</option></select></label><select id="la-${mode}-topic"><option value=""></option><option value="教育">教育</option></select><input id="la-${mode}-search"></div><div id="la-${mode}-cards"></div><div id="la-${mode}-progress"></div><div id="la-${mode}-count"></div>${['reading','writing','listening','speaking','phrases','vocabulary','shared'].map(k=>`<span id="${mode}-${k}-list"></span>`).join('')}<div id="la-${mode}-extras"></div></section>`;
 const tests=Object.keys(fixtureData.tests).map(id=>`<section class="panel" id="test-${id}" data-la-owner="tests"><button data-test-start="${id}"></button><button data-test-submit="${id}"></button><button data-test-retry="${id}"></button><output data-test-clock></output><div data-test-progress></div><div class="la-test-body" hidden><section data-test-part="${id}"><div data-test-part-progress></div><textarea data-save="test-${id}-1" data-test-answer="${id}" data-question="1"></textarea>${id==='speaking'?'<button data-record="s"></button><button data-stop="s" disabled></button><input data-upload="s">':''}</section></div><div class="la-test-result" hidden></div><div data-test-reference hidden></div><details data-test-history></details></section>`).join('');
 const {window,document}=parseHTML(`<html><body><aside id="workspace-navigation"><button data-go="guide"></button><button data-go="study"></button><button data-go="practice"></button><button data-go="tests"></button></aside><div id="current-page-label"></div><main><section class="panel" id="guide"><div id="la-resume"></div><ul id="la-today-list"></ul><div id="la-today-progress"></div><div data-project="synthetic-project"><div data-project-progress></div></div></section><section class="panel" id="plan"><ul id="la-plan-list"></ul></section>${filters('study')}${filters('practice')}<section class="panel" id="lesson-panel"><h2 id="old-heading">旧页面大标题</h2><article id="lesson-one" data-learning-unit="lesson-one"><input type="checkbox" data-save="read-one"><div data-unit-progress="lesson-one"></div></article><article id="other-lesson">无关内容</article></section><section class="panel" id="practice-panel"><article id="practice-one" data-learning-unit="practice-one"><textarea data-save="q-one"></textarea><button data-la-unknown="q-one"></button><details id="gate-one" data-answer-gate='["q-one"]'><summary>核对</summary><div class="la-gate-content" hidden>合成参考答案</div></details><div data-unit-progress="practice-one"></div></article></section><section class="panel" id="tests"><button id="la-start-mock"></button><div id="la-mock-progress"></div></section>${tests}<input type="hidden" id="learning-adjust-state" data-save="learning-adjust-state"><p id="la-notice" hidden></p></main><script id="learning-adjust-data" type="application/json">${JSON.stringify(localData)}</script></body></html>`);
 // linkedom has no layout, playback or native select interaction. Only model their input value.
 for(const n of document.querySelectorAll('select'))Object.defineProperty(n,'value',{value:'',writable:true});
 for(const n of document.querySelectorAll('[data-save]')){const v=store.value.fields[n.dataset.save];if(v!==undefined){if(n.type==='checkbox')n.checked=!!v;else n.value=String(v);}}
 document.addEventListener('input',e=>{const n=e.target;if(n.dataset.save&&!store.failWrite)store.value={...store.value,fields:{...store.value.fields,[n.dataset.save]:n.type==='checkbox'?n.checked:n.value}};});
 const location={hash:'#guide'},localStorage={getItem:()=>JSON.stringify(store.value)};
 window.IELTSLearning=M;window.confirm=()=>true;
 const context=vm.createContext({window,document,location,localStorage,Event:window.Event,requestAnimationFrame:f=>f(),setTimeout:()=>1,clearTimeout:()=>{},setInterval:()=>1,console});
 vm.runInContext(fs.readFileSync('./learning-adjust.js','utf8'),context,{filename:'learning-adjust.js'});
 const q=s=>document.querySelector(s),click=s=>{const n=typeof s==='string'?q(s):s;const e=new window.Event('click',{bubbles:true,cancelable:true});n.dispatchEvent(e);return e;},input=(selector,v)=>{const n=q(selector);if(n.type==='checkbox')n.checked=v;else n.value=v;n.dispatchEvent(new window.Event('input',{bubbles:true}));};
 const route=hash=>{location.hash='#'+hash;window.dispatchEvent(new window.Event('hashchange'));};
 return{store,document,window,location,q,click,input,route,state:()=>M.read(store.value.fields['learning-adjust-state']||'')};
}
const results=[];function test(name,f){try{f();results.push({name,pass:true});console.log('PASS',name)}catch(e){results.push({name,pass:false,error:e.stack});console.log('FAIL',name,e.message)}}
test('initial controller boot and grouped entry points',()=>{const a=boot();assert.equal(a.q('#la-study-cards').children.length,1);assert.equal(a.q('#la-practice-cards').children.length,1);assert.equal(a.q('#test-reading .la-test-body').hidden,true);});
test('select skill and add/remove a real activity from today',()=>{const a=boot();a.click('#la-study-cards button');a.click('#la-study-cards .la-card-actions button');assert.deepEqual(a.state().today,['lesson-one']);assert.match(a.q('#la-today-list').textContent,/合成讲解/);assert.match(a.q('#la-plan-list').textContent,/合成讲解/);a.click('#la-today-list button');assert.deepEqual(a.state().today,[]);});
test('blank answer disclosure is blocked and explicit unknown unlocks',()=>{const a=boot();assert.equal(a.click('#gate-one summary').defaultPrevented,true);assert.equal(a.q('.la-gate-content').hidden,true);a.click('[data-la-unknown]');assert.equal(a.click('#gate-one summary').defaultPrevented,false);assert.equal(a.q('.la-gate-content').hidden,false);assert.equal(a.state().checked['gate-one'].answers['q-one'],'暂时不会');});
test('reload preserves first answer despite later edit',()=>{const a=boot();a.input('[data-save="q-one"]','my first');a.click('#gate-one summary');a.input('[data-save="q-one"]','after feedback');const b=boot(a.store.value);b.click('#gate-one summary');assert.equal(b.state().checked['gate-one'].answers['q-one'],'my first');});
test('failed saving cannot unlock answers',()=>{const a=boot(undefined,true);a.input('[data-save="q-one"]','an attempt');a.click('#gate-one summary');assert.equal(a.q('.la-gate-content').hidden,true);assert.match(a.q('#la-notice').textContent,/未能保存/);});
test('test start submit retry keeps first result and clears draft',()=>{const a=boot();a.click('[data-test-start="reading"]');const started=a.state().tests.reading.start;a.click('[data-test-start="reading"]');assert.equal(a.state().tests.reading.start,started);a.input('[data-test-answer="reading"]','right');a.click('[data-test-submit="reading"]');assert.equal(a.q('[data-test-answer="reading"]').readOnly,true);assert.equal(a.q('#test-reading .la-test-result').hidden,false);a.click('[data-test-retry="reading"]');assert.equal(a.q('[data-test-answer="reading"]').value,'');assert.equal(a.state().tests.reading.history[0].answers['1'],'right');});
test('new full mock archives draft only once and queues later subjects',()=>{const a=boot();a.click('[data-test-start="reading"]');a.input('[data-test-answer="reading"]','old draft');a.click('#la-start-mock');assert.equal(a.state().tests.reading.status,'queued');assert.equal(a.state().tests.reading.history.length,1);assert.equal(a.state().tests.reading.history[0].answers['1'],'old draft');assert.equal(a.state().tests.listening.status,'running');assert.equal(a.state().tests.speaking.status,'queued');assert.equal(a.q('[data-test-answer="reading"]').value,'');});
test('cannot submit during active speaking recording',()=>{const a=boot();a.click('[data-test-start="speaking"]');a.q('[data-stop]').disabled=false;a.click('[data-test-submit="speaking"]');assert.equal(a.state().tests.speaking.status,'running');assert.match(a.q('#la-notice').textContent,/结束/);});
test('stored damaged schedule is not overwritten',()=>{const seed={version:1,fields:{'learning-adjust-state':'{damaged'},snapshots:{}};const a=boot(seed);a.click('[data-test-start="reading"]');assert.equal(a.store.value.fields['learning-adjust-state'],'{damaged');assert.equal(a.q('#test-reading .la-test-body').hidden,true);});
test('v2 first entrance has exactly four skills and no mixed task list',()=>{const a=boot(undefined,false,2);a.route('practice');assert.deepEqual([...a.q('#la-practice-cards').querySelectorAll('h2')].map(n=>n.textContent),['听力','阅读','写作','口语']);assert.equal(a.q('#practice .la-toolbar').hidden,true);assert.equal(a.q('#la-practice-cards').querySelector('[data-catalog-unit]'),null);});
test('v2 choosing a skill reveals only its actual activities with a return path',()=>{const a=boot(undefined,false,2);a.route('practice-reading-list');assert.equal(a.q('#practice .la-heading h1').textContent,'练习 · 阅读');assert.equal(a.q('#practice .la-toolbar').hidden,false);assert.equal(a.q('#la-practice-cards').querySelectorAll('[data-catalog-unit]').length,1);assert.equal(a.q('#la-practice-location a').getAttribute('href'),'#practice');a.route('practice');assert.equal(a.q('#la-practice-cards').querySelectorAll('h2').length,4);});
test('v2 opening one lesson conceals old sibling content and retains a subject return path',()=>{const a=boot(undefined,false,2);a.route('lesson-one');assert.equal(a.q('#other-lesson').hasAttribute('data-la-focus-hidden'),true);assert.equal(a.q('#old-heading').hasAttribute('data-la-focus-hidden'),true);assert.equal(a.q('#lesson-one').hasAttribute('data-la-focus-hidden'),false);assert.equal(a.q('.la-focus-nav a').getAttribute('href'),'#study-reading-list');assert.equal(a.q('[data-go="study"]').getAttribute('aria-current'),'page');});
fs.writeFileSync('./research/learning-adjust-dom-qa-20260920.json',JSON.stringify({fixture:'synthetic only; no browser and no actual learner data',controllerPath:'learning-adjust.js',controllerSHA256:require('node:crypto').createHash('sha256').update(fs.readFileSync('./learning-adjust.js')).digest('hex'),navigationVersionsTested:[0,2],results,passed:results.filter(x=>x.pass).length,total:results.length},null,2));
if(results.some(x=>!x.pass))process.exitCode=1;
