const {chromium}=require('C:/Users/Admin1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert'),path=require('path'),{pathToFileURL}=require('url');
const book='C:/Users/Admin1/Documents/Codex/2026-09-12/referenced-chatgpt-conversation-this-is-an/outputs/IELTS-四科学习册/开始学习.html';
const out=path.join(__dirname,'learning-upgrade-qa');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 try{
  await page.goto(pathToFileURL(book).href+'#vocabulary',{waitUntil:'load'});
  await page.evaluate(()=>{const p=document.createElement('p');p.id='qa-word';p.textContent='sustainable';document.querySelector('#vocabulary').prepend(p);});
  await page.locator('#qa-word').scrollIntoViewIfNeeded();
  const select=()=>page.evaluate(()=>{const p=document.querySelector('#qa-word'),r=document.createRange();r.selectNodeContents(p);getSelection().removeAllRanges();getSelection().addRange(r);p.dispatchEvent(new PointerEvent('pointerup',{bubbles:true}));});
  await select();await page.locator('#selection-lookup').click();await page.waitForFunction(()=>document.querySelector('#lookup-result').textContent.includes('ECDICT')||document.querySelector('#lookup-result .dictionary-entry'));
  assert(await page.locator('#word-lookup').isVisible());await page.locator('#lookup-favorite').click();assert.equal(await page.evaluate(()=>IELTSLookup.getHistory().find(x=>x.term==='sustainable').favorite),true);checks.push({name:'selected word opens lookup and can be collected',pass:true});
  await page.locator('#lookup-close').click();await select();await page.locator('#selection-collect').click();await page.waitForFunction(()=>document.querySelector('#selection-collect').textContent.includes('已收藏'));assert.equal(await page.evaluate(()=>IELTSLookup.getHistory().filter(x=>x.term==='sustainable').length),1);checks.push({name:'direct selection collection deduplicates the word',pass:true});
  await page.evaluate(()=>{getSelection().removeAllRanges();location.hash='vocabulary-review';});await page.locator('#vr-start').click();assert.equal(await page.locator('#vr-stage .vr-meaning').count(),0);await page.getByRole('button',{name:'查看释义与原句',exact:true}).click();await page.locator('[data-vr-grade="known"]').click();await page.getByRole('button',{name:'返回单词表',exact:true}).click();
  const due=await page.evaluate(()=>IELTSLookup.getHistory()[0].review.dueAt);await page.reload({waitUntil:'load'});assert.equal(await page.evaluate(()=>IELTSLookup.getHistory()[0].review.dueAt),due);await page.screenshot({path:path.join(out,'vocabulary-desktop.png'),fullPage:false});checks.push({name:'review hides answers, schedules and survives reload',pass:true});
  await page.evaluate(()=>location.hash='writing-workbench');await page.screenshot({path:path.join(out,'writing-desktop.png'),fullPage:false});assert.equal(await page.locator('#writing-workbench').isVisible(),true);
  await page.locator('#ww-task-picker').selectOption('ww-housing');await page.locator('#ww-housing [data-save="ww-housing-first"]').fill('Advertising can support small businesses by helping them reach potential customers.');
  await page.locator('#ww-housing [data-save="ww-housing-first"]').evaluate(e=>{e.focus();e.setSelectionRange(0,44);e.dispatchEvent(new PointerEvent('pointerup',{bubbles:true}));});await page.locator('#selection-translate').waitFor({state:'visible'});checks.push({name:'selecting an essay excerpt offers translation',pass:true});
  await page.evaluate(()=>{document.querySelector('#selection-toolbar').hidden=true;location.hash='sentence-learning';});await page.locator('[data-open-sentence]').click();await page.locator('#sentence-source').fill('Public transport can reduce traffic congestion.');await page.locator('#sentence-translate').click();await page.waitForFunction(()=>!document.querySelector('#sentence-translate').disabled,{timeout:23000});
  const translated=await page.locator('#sentence-result').inputValue();checks.push({name:'live translation from local file browser',pass:!!translated,result:translated||await page.locator('#sentence-status').textContent()});if(translated){await page.locator('#sentence-save').click();}
  await page.locator('#sentence-close').click();await page.evaluate(()=>location.hash='records');
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('[data-export="json"]').last().click()]);const backup=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert(backup.fields['lookup-history-v1']);assert(backup.fields['ww-housing-first']);if(translated)assert(backup.fields['sentence-collection-v1']);
  const expected=backup.fields['lookup-history-v1'];await page.locator('#import-state').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForLoadState('load');await page.waitForFunction(expected=>document.querySelector('#lookup-history-store').value===expected,expected);checks.push({name:'whole-book export and import include all three new feature records',pass:true});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>location.hash='writing-workbench');await page.screenshot({path:path.join(out,'writing-mobile.png'),fullPage:false});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);checks.push({name:'writing workbench fits mobile viewport',pass:true});
  assert.deepEqual(errors,[]);checks.push({name:'no uncaught page errors',pass:true});
 }catch(e){checks.push({name:'integration smoke',pass:false,error:e.stack});}finally{await context.close();await browser.close();fs.writeFileSync(path.join(out,'integration-browser-tests.json'),JSON.stringify(checks,null,2));console.log(JSON.stringify(checks,null,2));if(checks.some(c=>!c.pass))process.exitCode=1;}
})();

