const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const {parseHTML}=require('D:/IELTS-Work/learning-adjust-20260920/synthetic-tests/node_modules/linkedom');
const sourcePath='D:/IELTS-Work/learning-adjust-20260920/开始学习-ui-final.html';
const raw=fs.readFileSync(sourcePath),html=raw.toString('utf8');
const checks=[];function check(name,fn){try{const detail=fn();checks.push({name,status:'pass',detail});}catch(e){checks.push({name,status:'needs_fix',error:e.stack,actual:e.actual,expected:e.expected});}}
function fixture({initial=null,quota=false,hash='#study'}={}){
 const {document,window:w}=parseHTML(html),callbacks={},timers=[],rafs=[];let storage=initial,reloads=0,downloads=[]; for(const n of document.querySelectorAll('[type="checkbox"]'))n.checked=n.hasAttribute('checked');
 Object.defineProperty(w.HTMLSelectElement.prototype,'value',{configurable:true,get(){if(this.__syntheticValue!==undefined)return this.__syntheticValue;const o=[...this.querySelectorAll('option')];return o.find(x=>x.selected)?.getAttribute('value')??o[0]?.getAttribute('value')??o[0]?.textContent??''},set(v){this.__syntheticValue=String(v)}});
 w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLElement.prototype.focus=function(){};w.HTMLElement.prototype.getClientRects=function(){return[{}]};w.HTMLElement.prototype.getBoundingClientRect=function(){return {top:1,bottom:2,left:1,right:2}};w.HTMLElement.prototype.pause=function(){};
 const loc={hash,reload(){reloads++}},win={addEventListener(t,fn){(callbacks[t]??=[]).push(fn)},scrollTo(){},confirm:()=>true,scrollY:0,innerHeight:900,innerWidth:1200};
 const localStorage={getItem(k){return k==='ielts-finished-book-v1'?storage:null},setItem(k,v){if(quota)throw Error('QuotaExceededError');if(k==='ielts-finished-book-v1')storage=v}};
 const ctx={window:win,document,location:loc,localStorage,navigator:{},Blob,URL:{createObjectURL(b){downloads.push(b);return'blob:synthetic'},revokeObjectURL(){}},Event:w.Event,Date,JSON,console,confirm:()=>true,setTimeout:fn=>{timers.push(fn);return timers.length},clearTimeout(){},setInterval:fn=>{timers.push(fn);return timers.length},clearInterval(){},requestAnimationFrame:fn=>rafs.push(fn),TextEncoder,AbortController};
 ctx.performance={now:()=>1000};ctx.HashChangeEvent=w.Event;win.dispatchEvent=e=>{for(const fn of callbacks[e.type]||[])fn(e)};win.location=loc;win.localStorage=localStorage;vm.createContext(ctx);
 const importer=document.querySelector('#import-state'); const oldAdd=importer.addEventListener.bind(importer); importer.addEventListener=(type,fn)=>{if(type==='change')importer.syntheticChange=fn;else oldAdd(type,fn)};
 const scripts=[...document.querySelectorAll('script')];
 const run=i=>vm.runInContext(scripts[i].textContent,ctx,{filename:'actual-script-'+i+'.js'});
 const click=n=>n.dispatchEvent(new w.Event('click',{bubbles:true}));
 const input=(key,value)=>{const n=document.querySelector(`[data-save="${key}"]`);if(n.type==='checkbox')n.checked=value;else n.value=value;n.dispatchEvent(new w.Event('input',{bubbles:true}));return n};
 const flush=()=>{let c=0;while(rafs.length&&c++<100)rafs.shift()()};
 const route=hash=>{loc.hash=hash;for(const fn of callbacks.hashchange||[])fn();flush()};
 return{callbacks,document,window:win,ctx,run,click,input,flush,route,get storage(){return storage},get reloads(){return reloads},downloads,setQuota(v){quota=v}};
}
function boot(options={}){
 const f=fixture(options);f.run(0);f.run(1);f.run(2);f.run(12);
 const scripts=[...f.document.querySelectorAll('script')];f.named=id=>f.run(scripts.findIndex(n=>n.id===id));
 f.named('learning-adjust-model-script');f.named('learning-adjust-script');f.flush();
 f.q=s=>f.document.querySelector(s);f.qa=s=>[...f.document.querySelectorAll(s)];f.data=JSON.parse(f.q('#learning-adjust-data').textContent);
 f.state=()=>JSON.parse(JSON.parse(f.storage).fields['learning-adjust-state']);
 f.visible=n=>{for(let p=n;p;p=p.parentElement)if(p.hidden||p.hasAttribute('data-la-focus-hidden')||p.classList?.contains('ui-filtered')||p.classList?.contains('la-hidden-legacy'))return false;return true};
 return f;
}
const f=boot();
check('Four primary entries and Study as the default route',()=>{assert.deepEqual(f.qa('#workspace-navigation nav [data-go]').map(n=>n.textContent.trim()),['学习','练习','测试','工作区']);f.route('');assert.equal(f.q('main>.panel:not([hidden])').id,'study');assert.equal(f.q('[data-go="study"]').getAttribute('aria-current'),'page');});
check('Study and Practice roots show four subjects, no mixed activity list',()=>{for(const mode of ['study','practice']){f.route('#'+mode);assert.deepEqual(f.qa('#la-'+mode+'-cards h2').map(n=>n.textContent),['听力','阅读','写作','口语']);assert.equal(f.qa('#la-'+mode+'-cards [data-catalog-unit]').length,0);assert(f.q('#'+mode+' .la-toolbar').hidden);assert(!f.q('#la-'+mode+'-cards').textContent.includes('Task 1'));}});
check('Writing has a separate Task 1 / Task 2 picker before content',()=>{for(const mode of ['study','practice']){f.route('#'+mode+'-writing-list');assert.deepEqual(f.qa('#la-'+mode+'-cards h2').map(n=>n.textContent),['Task 1','Task 2']);assert.equal(f.qa('#la-'+mode+'-cards [data-catalog-unit]').length,0);for(const skill of ['writing1','writing2']){f.route('#'+mode+'-'+skill+'-list');const shown=f.qa('#la-'+mode+'-cards [data-catalog-unit]');assert(shown.length);assert(shown.every(n=>f.data.units.find(u=>u.id===n.dataset.catalogUnit).skill===skill));assert(f.q('#la-'+mode+'-location a[href="#'+mode+'-writing-list"]'));}}});
check('Every unit appears exactly once in its own mode and subject catalog',()=>{let total=0;for(const mode of ['study','practice'])for(const skill of [...new Set(f.data.units.filter(u=>u.mode===mode).map(u=>u.skill))]){f.route('#'+mode+'-'+skill+'-list');const expected=f.data.units.filter(u=>u.mode===mode&&u.skill===skill).map(u=>u.id).sort();const shown=f.qa('#la-'+mode+'-cards [data-catalog-unit]').map(n=>n.dataset.catalogUnit).sort();assert.deepEqual(shown,expected,mode+'/'+skill);total+=shown.length;}assert.equal(total,218);return{catalogUnits:total}});
check('Filters are scoped and returning to a category clears earlier filters',()=>{f.route('#practice-reading-list');const pick=f.q('#la-practice-topic'),choice=[...pick.querySelectorAll('option')].find(n=>n.value);pick.value=choice.value;pick.dispatchEvent(new f.ctx.Event('input',{bubbles:true}));assert(f.qa('#la-practice-cards [data-catalog-unit]').every(n=>f.data.units.find(u=>u.id===n.dataset.catalogUnit).topic===choice.value));f.q('#la-practice-search').value='no results 76543';f.q('#la-practice-search').dispatchEvent(new f.ctx.Event('input',{bubbles:true}));assert(f.q('#la-practice-cards .la-empty'));f.route('#practice-listening-list');assert.equal(f.q('#la-practice-search').value,'');assert(f.qa('#la-practice-cards [data-catalog-unit]').length);});
check('All unit deep links show their own content and matching return navigation',()=>{let total=0;for(const u of f.data.units){f.route('#'+u.id);const node=f.document.getElementById(u.id);assert.equal(f.q('main>.panel:not([hidden])').id,node.closest('main>.panel').id,u.id);assert(f.visible(node),'Unit hidden: '+u.id);const nav=f.q('.la-focus-nav');assert.equal(nav.querySelector('a').getAttribute('href'),'#'+u.mode+'-'+u.skill+'-list',u.id);assert(f.q('#current-page-label').textContent.includes(u.title),u.id);const siblings=f.data.units.filter(x=>x.id!==u.id&&f.document.getElementById(x.id).closest('main>.panel')===node.closest('main>.panel'));assert(siblings.every(x=>!f.visible(f.document.getElementById(x.id))),u.id+' exposes another unit');total++;}return{deepLinks:total}});
check('Unit progress updates after actual input and ignores optional notes',()=>{const id='listening-new-new-listening-campus-notes',u=f.data.units.find(x=>x.id===id);f.route('#'+id);const out=f.q('[data-unit-progress="'+id+'"]');assert(out.textContent.includes('0 / 5'));f.input('resource-note-new-listening-campus-notes','an optional note');f.flush();assert(out.textContent.includes('0 / 5'));f.input(u.steps[0].key,'attempt');f.flush();assert(out.textContent.includes('1 / 5'));});
check('Phrase and vocabulary navigation restores visible cards',()=>{for(const id of ['usage-04','learn-189','usage-12','learn-190']){f.route('#'+id);assert(f.visible(f.document.getElementById(id)),id);}});
check('Daily start screen and learning projects have clear Study ownership',()=>{for(const id of ['guide','learning-projects','course-window']){f.route('#'+id);assert.equal(f.q('[data-go="study"]').getAttribute('aria-current'),'page');assert(f.q('#'+id+' a[href="#study"]'));}f.route('#guide');assert(f.visible(f.q('#daily-study-home')));assert(!f.visible(f.q('.home-top')));f.route('#learning-projects');assert.equal(f.qa('#learning-projects [data-project]').length,3);});
check('Workspace entries retain destinations and return paths',()=>{f.route('#workspace');for(const a of f.qa('#workspace .la-workspace-grid a')){const target=a.getAttribute('href').slice(1);f.route('#'+target);assert(!f.document.getElementById(target).hidden,target);assert(f.q('#'+target+' a[href="#'+(target==='course-window'?'study':'workspace')+'"]'));}f.route('#workspace');});
check('Tests root contains four disciplines and one full combination action',()=>{f.route('#tests');assert.deepEqual(f.qa('#tests>.la-grid h2').map(n=>n.textContent),['听力','阅读','写作','口语']);for(const id of ['listening','reading','writing','speaking']){f.route('#test-'+id);assert.equal(f.q('[data-go="tests"]').getAttribute('aria-current'),'page');assert(f.q('#test-'+id+' a[href="#tests"]'));assert(f.q('#test-'+id+' .la-test-body').hidden);}assert(f.q('#la-start-mock'));assert.equal(f.qa('[data-test-answer="listening"]').length,40);assert.equal(f.qa('[data-test-answer="reading"]').length,40);});
check('Failed commits keep cases and supplementary drafts editable, references locked',()=>{f.setQuota(true);for(const [selector,answers,submit,done,reference] of [['[data-enrichment]','[data-save$="-answer"]','[data-enrich-freeze]','[data-save$="-frozen"]','.enrichment-feedback'],['.exam-case','[data-case-answer]','[data-case-submit]','[data-case-done]','.case-feedback']]){const u=f.q(selector);for(const a of u.querySelectorAll(answers))f.input(a.dataset.save,'attempt');const before=f.storage;f.click(u.querySelector(submit));assert(!u.querySelector(done).checked);assert.equal(f.storage,before);const feedback=u.querySelector(reference);if(feedback)assert(feedback.hidden);}f.setQuota(false);});
check('Successful case submission immediately refreshes progress',()=>{const u=f.q('.exam-case'),id=u.id;for(const a of u.querySelectorAll('[data-case-answer]'))f.input(a.dataset.save,'attempt');f.click(u.querySelector('[data-case-submit]'));assert(u.querySelector('[data-case-done]').checked);assert(f.q('[data-unit-progress="'+id+'"]').textContent.includes('100%'));});
check('Listening full key accepts letters, labels and tutor variants',()=>{const M=f.window.IELTSLearning,key=f.data.tests.listening.key;assert.equal(Object.keys(key).length,40);const answers=Object.fromEntries(Object.entries(key).map(([q,v])=>[q,v[0]]));assert.equal(M.score(answers,key).correct,40);answers['15']='D';answers['37']='tutor';assert.equal(M.score(answers,key).correct,40);answers['37']='tutors';assert.equal(M.score(answers,key).correct,40);});
check('Test submission and a new round preserve history',()=>{f.click(f.q('[data-test-start="reading"]'));f.route('#test-reading');f.input('full-test-reading-q1','mining');f.click(f.q('[data-test-submit="reading"]'));assert(f.q('[data-test-answer="reading"]').readOnly);assert(!f.q('#test-reading .la-test-result').hidden);f.click(f.q('[data-test-retry="reading"]'));assert.equal(f.q('[data-test-answer="reading"]').value,'');assert.equal(f.state().tests.reading.history[0].answers['1'],'mining');});
check('Daily module boots, starts, pauses and resumes through categorized content',()=>{f.named('daily-study-model-script');f.named('daily-study-script');f.flush();f.route('#guide');f.click(f.q('#ds-start'));const record=()=>JSON.parse(JSON.parse(f.storage).fields['daily-study-state']);assert.equal(record().session.status,'active');const target=record().session.steps[0].target;f.route('#'+target);assert(f.visible(f.document.getElementById(target)));f.click(f.q('#ds-pause'));assert.equal(record().session.status,'paused');f.click(f.q('#ds-pause'));assert.equal(record().session.status,'active');f.route('#study');assert.equal(record().session.status,'paused');f.route('#guide');f.click(f.q('#ds-start'));f.route('#'+target);assert.equal(record().session.status,'active');});
check('Daily catalog targets all survive and are not hidden by unit focusing',()=>{const catalog=JSON.parse(f.q('#daily-study-catalog').textContent);let count=0;for(const item of catalog)for(const stage of item.stages){const targets=typeof stage.target==='string'?[stage.target]:Object.values(stage.target);for(const id of new Set(targets)){assert(f.document.getElementById(id),id);f.route('#'+id);const n=f.document.getElementById(id);assert(!n.closest('[data-la-focus-hidden]'),id);count++;}}return{dailyTargets:count}});
check('Existing saved values and daily state survive a simulated reload',()=>{const before=f.storage,g=boot({initial:before});assert.equal(g.q('[data-save="resource-note-new-listening-campus-notes"]').value,'an optional note');assert.equal(g.q('#daily-study-state').value,JSON.parse(before).fields['daily-study-state']);assert(g.q('[data-case-done]').checked);});
const out={sourcePath,sha256:crypto.createHash('sha256').update(raw).digest('hex'),method:'Actual candidate scripts in Node/linkedom with synthetic storage; no real browser, layout engine, user localStorage or microphone.',checks,passed:checks.filter(x=>x.status==='pass').length,total:checks.length};fs.writeFileSync('C:/Users/Admin1/Documents/ChatGPT/ielts/research/navigation-ui-final-tests-20260920.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));if(out.passed!==out.total)process.exitCode=1;

